### ISSUE TITLE
How to start client

### ISSUE THREAD

**Issue by Eutepria** [wtfblub/NetspherePirates#10]
![s4 league](https://cloud.githubusercontent.com/assets/18445680/14499937/fdc1de2c-0197-11e6-94db-96222000efc5.PNG)

**Comment by rabi3123** [comment]
This is Not A Problem!
You need just the command bat that include the arguments to start the client 

To Fix this You have to Download this into the client folder:

http://www109.zippyshare.com/v/c7DdeLVo/file.html

**Comment by huenato** [comment]
create a shortcut of S4Client.exe to your desktop and add this line into the Properties > Target
`-rc:eu -lac:eng -auth_server_ip:127.0.0.1`

**Comment by Eutepria** [comment]
Sorry about this guys ;;, and thank you so much <3. Btw, was this posted on twitter or something? because i didn't see 'WTFBlub' mentioning anything about this problem, nor did i see any instructions which i should follow to launch the game properly. Once again, thank you <3

**Comment by Eutepria** [comment]
Also, where do i register? is there a specific website for this server?

**Comment by wtfblub** [comment]
A setup guide can be found [here](https://github.com/wtfblub/NetspherePirates/wiki/Setup-from-a-pre-built-package)
