### ISSUE TITLE
Help me please.                                          ساعدني من فضلك.

### ISSUE THREAD

**Issue by jazzup02** [wtfblub/NetspherePirates#102]
i need files this picture
![](https://cloud.githubusercontent.com/assets/19153597/19459198/eba0f2b6-94d9-11e6-8d2b-20962978d241.jpg)
Pleaseeeeeeeeeeeeeeee

**Comment by jazzup02** [comment]
Please @wtfblub & @BioAleks

**Comment by wtfblub** [comment]
Issues are not meant for asking for stuff like this.
