### ISSUE TITLE
I need a tutorial about: how to add new weapons(skins force pack) in the shop

### ISSUE THREAD

**Issue by fealing** [wtfblub/NetspherePirates#103]
I use the s4 league dark force client (the same thing)i can add weapons in the inventory like the monk's katana twin blade(force pack) a others. But i can't add this weapons in the shop for buy, i don't want add every weapon what i want in the database of the game(for one acount).
-Sqlite
-S4 League dark force client
-Database sqlite editor
-Database mysql editor
-xampp7
-Resource tool(thanks denny9700)
-S4_server_editor
Other thing?
(Sorry for the bad english,i am from venezuela)

**Comment by FreeDenny9700** [comment]
Library in Resource Tool isn't updated. Please replace all DLL with new Blub DLL.
You can take new DLL from Blub project.

**Comment by fealing** [comment]
Were i can found that files and how i can add new weapons in the shop(the original question).

**Comment by FreeDenny9700** [comment]
download Blub Code, extract all, go to library directory, move all files to my directory

**Comment by fealing** [comment]
i download the file:netspherepirates-master.zip,extract all to you resource tool,is correct?

**Comment by FreeDenny9700** [comment]
no, open library folder and copy all to resource tool library

**Comment by fealing** [comment]
the database ?(.db files)

**Comment by HARUWEEN** [comment]
do you have skype? or discord perhaps? i can help you

**Comment by fealing** [comment]
no men, i don't have skype but facebook yes.

**Comment by HARUWEEN** [comment]
lol sorry can't help you then

**Comment by fealing** [comment]
we can talk in another platform ?

**Comment by fealing** [comment]
Dude i have skype now.

**Comment by HARUWEEN** [comment]
add me jammy01180

**Comment by fealing** [comment]
ok

**Comment by HARUWEEN** [comment]
@wtfblub close this my dear friend, i'm helping this guy
