### ISSUE TITLE
Invalid DecryptCounter ???

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#105]
Hi Blub.
Interesting error i say today (for client).
ProudNet.ProudException: Invalid DecryptCounter! Message: 1 Client: 1
Client no be dropped and all work.

[error.txt](https://github.com/wtfblub/NetspherePirates/files/710747/error.txt)

**Comment by HARUWEEN** [comment]
LOL

**Comment by wtfblub** [comment]
#115

**Comment by BioAleks** [comment]
I no use Linux, but error 115 for Linux. Yes, same error, but change title in 115.
