### ISSUE TITLE
2 Reports (possible related?)

### ISSUE THREAD

**Issue by Anutim** [wtfblub/NetspherePirates#108]
Yo, whenever I host, whether it be online, or offline. All players playing on my server get audio position issues. When a player is e.g. 20ft away, it sounds like he's right in your ear. That sorta stuff, happens with all sounds that are triggered from player to player.

The other issue are these messages:
http://imgur.com/a/9jy4u
The 00 word occurs whenever there's 1+ player(s) in a room.
The other one that posts 3 words occur with 2+ players in a room.

The OS I host on is Win 7 SP1 with the latest .NET update from Windows Update.

EDIT: Perhaps I should note that this has been occuring on all versions I've tried hosting on, whether it's huenatos forks or your original.

**Comment by wtfblub** [comment]
Not related and the audio issues are client side bugs.
