### ISSUE TITLE
Blublib documentation? or any other source?

### ISSUE THREAD

**Issue by nagyation** [wtfblub/NetspherePirates#111]

**Comment by wtfblub** [comment]
The BlubLib source i posted on your other issue is the only public source. Check the [dotnetty branch](https://github.com/wtfblub/NetspherePirates/tree/dotnetty) for the updated emulator using the latest BlubLib.

**Comment by nagyation** [comment]
I'm trying to contribute, so I want to understand things so I can manage to help :D
