### ISSUE TITLE
Dont Find a Server

### ISSUE THREAD

**Issue by gxgamerxg** [wtfblub/NetspherePirates#117]
I start at first auth.exe. After this i start game.exe than the start.bat.. now the game.exe crashes.
The game starts but at the Server list there is no Server. Can u help me? 
What in the game.exe file is: 
[Program->Main:33] Checking database...
[Program->FillShop:139] NoobMode: Filling the shop with items

Unbehandelte Ausnahme: System.TypeInitializationException: Der Typeninitialisierer für "Netsphere.Network.GameServer" hat eine Ausnahme verursacht. ---> System.IO.DirectoryNotFoundException: Ein Teil des Pfades "D:\Downloads Mega\FumbiClient\game\data\xml\_eu_channel_setting.x7" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path)
   bei Netsphere.Resource.ResourceLoader.Deserialize[T](String fileName) in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:Zeile 507.
   bei Netsphere.Resource.ResourceLoader.<LoadChannels>d__7.MoveNext() in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:Zeile 45.
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Netsphere.Resource.ResourceCache.GetChannels() in C:\projects\netspherepirates\src\Game\Resource\ResourceCache.cs:Zeile 76.
   bei Netsphere.Network.GameServer..ctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:Zeile 159.
   bei Netsphere.Network.GameServer..cctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:Zeile 30.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Netsphere.Network.GameServer.get_Instance()
   bei Netsphere.Program.FillShop() in C:\projects\netspherepirates\src\Game\Program.cs:Zeile 198.
   bei Netsphere.Program.Main() in C:\projects\netspherepirates\src\Game\Program.cs:Zeile 42.
[ResourceCache->GetChannels:72] Caching...
[Program->OnUnhandledException:114] UnhandledException
System.TypeInitializationException: Der Typeninitialisierer für "Netsphere.Network.GameServer" hat eine Ausnahme verursacht. ---> System.IO.DirectoryNotFoundException: Ein Teil des Pfades "D:\Downloads Mega\FumbiClient\game\data\xml\_eu_channel_setting.x7" konnte nicht gefunden werden.

**Comment by wtfblub** [comment]
https://github.com/wtfblub/NetspherePirates/wiki/Setup-from-a-pre-built-package

**Comment by gxgamerxg** [comment]
What did i have to do?
