### ISSUE TITLE
Wtfblub I have something very important to tell you

### ISSUE THREAD

**Issue by s4archivos** [wtfblub/NetspherePirates#120]
I can only tell you by skype as it is very important is about the s4league

**Comment by wtfblub** [comment]
You can send me a DM on [Twitter](https://twitter.com/wtfblub)

**Comment by s4archivos** [comment]
Is that it is the code to run the s4 league season 10 with a .bat

**Comment by wtfblub** [comment]
English please.

**Comment by s4archivos** [comment]
what?

**Comment by s4archivos** [comment]
I say I know how to open the s4league season 10.

And I want to show you to see if you can work the s4league season 10

**Comment by wtfblub** [comment]
Nothing special about that.

**Comment by s4archivos** [comment]
And you could work for the season 10 when the emulators are stable?

**Comment by HARUWEEN** [comment]
@s4archivos don't waste your time on opening season10 client if you need help with emulating?

**Comment by s4archivos** [comment]
https://github.com/HARUWEEN In some things, could you help me?

**Comment by HARUWEEN** [comment]
@s4archivos check your twitter
