### ISSUE TITLE
Expected ;

### ISSUE THREAD

**Issue by Neroli-realy** [wtfblub/NetspherePirates#123]
when i try to debug the solution it gives me this errors i do not know how to fix it i had fixed
all ather errors 

![capture](https://cloud.githubusercontent.com/assets/25514920/22664028/9cb64a3a-ecb7-11e6-8639-71dc4b92a767.PNG)
??

**Comment by Neroli-realy** [comment]
@wtfblub ??

**Comment by FreeDenny9700** [comment]
Version of Visual Studio?

**Comment by HARUWEEN** [comment]
This has nothing to do with version, it's just typo's lol

**Comment by wtfblub** [comment]
They're not typos. They're C# 6 features which require VS2015 or above.

**Comment by HARUWEEN** [comment]
They are typos, he made changes to the code that's what he told me.
