### ISSUE TITLE
Need tool to open file s4_Lua_decompiler

### ISSUE THREAD

**Issue by loma058** [wtfblub/NetspherePirates#126]
need to open file .lua 
all file Encrypted

**Comment by FreeDenny9700** [comment]
Use Unluac.jar for decompile lua file. This is the command into CMD: 

Java -jar Unluac.jar Original_file_path > Decompiled_file_path

Have fun

**Comment by loma058** [comment]
need jave jdk and Eclipse or no 
and thank you
