### ISSUE TITLE
Pants variation 66 does not exist

### ISSUE THREAD

**Issue by Demon0no** [wtfblub/NetspherePirates#127]
I get the above mentioned error when trying to create a character with a different variation of pants.
Depending on what variation I chose I either get 66, or 33. The important part of the default_item.x7 is as follows:

    <male name_key="MALE">
    	
    	<item category="1" sub_category="0" number="1" variation="0">hair</item>
    	<item category="1" sub_category="0" number="1" variation="1">hair</item>
    	<item category="1" sub_category="0" number="1" variation="2">hair</item>
    	<item category="1" sub_category="0" number="1" variation="3">hair</item>
    	<item category="1" sub_category="0" number="1" variation="4">hair</item>
    	
    	<item category="1" sub_category="1" number="3" variation="0">face</item>
    	<item category="1" sub_category="1" number="4" variation="0">face</item>
    	
    	<item category="1" sub_category="2" number="24" variation="0">coat</item>
    	<item category="1" sub_category="2" number="24" variation="1">coat</item>
    	<item category="1" sub_category="2" number="24" variation="2">coat</item>
    	
    	<item category="1" sub_category="3" number="21" variation="0">pants</item>
    	<item category="1" sub_category="3" number="21" variation="1">pants</item>
    	<item category="1" sub_category="3" number="21" variation="2">pants</item>
    	
    	<item category="1" sub_category="4" number="2" variation="0">gloves</item>
    	
    	<item category="1" sub_category="5" number="2" variation="0">shoes</item>
    	
    </male>

I double checked these parts of the default_item.x7 in the server folder and the one in the client and they're both exactly this. Buying different variations of these pants through the shop works fine. I also can create a character with different variations of the Hair, ~~Face~~ and Coat. It's just the Pants that have problems for some reason.

Edit: I just realised the same thing happens with the face too. I thought I tested it, but apparently I didn't. If I try to create a player with the "Intense Style" face (Item Id: 1010004) and the variation 0 (like in the example above) the game-server is throwing the error: "Face variation 1 does not exist". On seeing this, I checked the alternate variations of the hair and coat again too and they definately DO work, so I'm kinda confused.

**Comment by BioAleks** [comment]
https://github.com/wtfblub/NetspherePirates/issues/79
