### ISSUE TITLE
Any way of contacts ? 

### ISSUE THREAD

**Issue by JustAGamer** [wtfblub/NetspherePirates#130]
Hello there ! I've been searching thorougly in the issues where I can find a way to contact members of this project (like discord or a skype group ?), but I've just found HARUWEEN's skype.

I'm a bit lost for the emulating, particularly for the database generation, and I want to see if I can help this amazing project ?

If HARUWEEN is still here sometime, can I have your agreement for adding you in skype ? Or is there any group discussion on discord that I can join ? Thank you for your understanding ! ^^

**Comment by wtfblub** [comment]
On [twitter](https://twitter.com/wtfblub) but don't expect fast answers. I rarely check my inbox.

FYI: Currently i'm the only one working on this project. There is no group/chat/server/etc.

**Comment by HARUWEEN** [comment]
lol what is this?

**Comment by HARUWEEN** [comment]
@wtfblub you're not the only one working on this project, lol. i am too

**Comment by HARUWEEN** [comment]
@JustAGamer you're saying you wanna help the project but you don't really understand it? or?

**Comment by JustAGamer** [comment]
For the moment, I'm trying to make it works, I mean for example, I'm stuck with the database thing : the auth.exe can't be launched cause it's lacking the auth.db in ../db, so I guess what I must do (install SQLite, use the script to create the database and compiling it, etc), but it's more like I want a confirmation of how you do it. I don't know if you know what I mean ? ^^'

**Comment by HARUWEEN** [comment]
I know what you mean, thanks for clarifying that. I just didn't understand the "I wanna help the project" part. And yeah you can add me on discord if you need help
discord: rxdy#1060
