### ISSUE TITLE
SceneContainer Error

### ISSUE THREAD

**Issue by iBreak97** [wtfblub/NetspherePirates#132]
Error : Function Write not work correctly.
VS Error : Unknown chunk type: 0x0001 StreamPosition: 266000

Error generated after read modified SCN exported with Write Function.
Thanks for your help

**Comment by FreeDenny9700** [comment]
Blub this is a binary differences between Original FryPan Storm Bat (Left) and Exported FryPan (Right).
I don't have modified file, i have only exported original file after this file are imported into SceneContainer.

![diff](https://cloud.githubusercontent.com/assets/19553583/23400660/02a647b6-fda5-11e6-9e43-5fce940bf611.png)

**Comment by FreeDenny9700** [comment]
Wtfblub how i can fix this error myself?

**Comment by wtfblub** [comment]
I dont have the time to look into it so you have to find out yourself.
https://github.com/wtfblub/NetspherePirates/tree/master/src/Netsphere.Resource/Scene

**Comment by FreeDenny9700** [comment]
Ah ok, thanks

**Comment by FreeDenny9700** [comment]
Error fixed.
ReadCString not work correctly with TextureName2.
Now it work perfectly

_Sent from my Google Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
