### ISSUE TITLE
game runs UDP P2P on rare occurrences?!

### ISSUE THREAD

**Issue by WAZAAAAA0** [wtfblub/NetspherePirates#133]
Me, users Shanzenos and Serene from S4MAX/BunkerS4 were able to play in peer-to-peer without the (R)(T) server, and yes the game was more responsive as a consequence. This came as a surprise because 99% of the playerbase has (R)(T).

I made sure this was 100% true by using a bit of WireShark sniffing and NetLimiter force lagging.
WireShark test: all player movement, attacks and even the room chat were UDP coming directly from the player's IP.
NetLimiter test: I became invincible by limiting the download stream of a player's IP so he couldn't communicate with me but I could still communicate with him. Classic S4 force lagging, it worked (overkilled Shanze and Serene with CS lol).

Upon further investigation, we have found out that enabling DMZ on our home routers affected this.
DMZ ON = P2P
DMZ OFF = (R)(T)

Here some related screenshots:
52.xxx.xxx.xxx = server
80.xxx.xxx.xxx = player
the game appeared to wait around 2 seconds before going from RT to P2P when first entering the room
https://i.imgur.com/ISJ4dJD.png
https://i.imgur.com/iaFfBBi.jpg
https://i.imgur.com/A4Eo85k.jpg

Maybe this is a problem related to how the private server admin has set up the server, and not the emulator itself? Now that I think about it, the first implementations of the official S4 servers after the Aeria migration AND PlayS4L both had forced (R)(T) for a little while before getting fixed, so it may seem likely.

I'm not sure if this whole report was of any help, but P2P is a must and S4 should use it more. Asking everyone to enable DMZ is not viable.

**Comment by wtfblub** [comment]
Can you get p2p with more than 1 player?

**Comment by WAZAAAAA0** [comment]
Yes, but I had to leave and re-enter my room once to make "tester" connect in P2P, because on the first join he was RT. Screenshot from every point of view:
73.xxx.xxx.xxx = tester/Shanzenos
109.xxx.xxx.xxx = Sunaru
https://i.imgur.com/mJOVN0Z.png
https://i.imgur.com/65fbnDC.jpg
https://i.imgur.com/cNRvMTD.png

**Comment by WAZAAAAA0** [comment]
Additional note: apparently, user Anutim has found out that opening UDP ports from 45000 to 65535 (which is supposed to be more or less the ports range randomly used by the game) is an alternative way to make P2P work without the use of DMZ.

**Comment by WAZAAAAA0** [comment]
Update: GameRaider has applied a P2P fix on his fork, these are the 3 related commits:
https://github.com/GameRaiderCC/NetspherePirates/commit/59a633663d9f537c6ea57d646abe6c7c7b2e16ad (Edited P2P success/jittrigger handling)
https://github.com/GameRaiderCC/NetspherePirates/commit/279a59ec8771d58ff68cb35a60d72c1fb67e25d8 (Completed PeerUdp_NotifyHolepunchSuccess handle)
https://github.com/GameRaiderCC/NetspherePirates/commit/da0051a2ca743955a419405ca9ce1f13869cc5ee (Edited P2P success/jittrigger handling)

In-game test:
![S4_20170807_013651.jpg](https://i.imgur.com/FHx6owt.jpg)

**Comment by wtfblub** [comment]
This is being tracked in #3

**Comment by WAZAAAAA0** [comment]
Fixed with https://github.com/wtfblub/NetspherePirates/pull/263 https://github.com/wtfblub/NetspherePirates/pull/264
YES
