### ISSUE TITLE
UDP listeners never reset, server only continues to use more for every room made/joined

### ISSUE THREAD

**Issue by shanzenos** [wtfblub/NetspherePirates#145]
Raider wanted me to post this for him, he found the following while debugging:
"The UDP listener bug is: every time you rejoin a room(even if you create/join a new one) the server creates a new listener --> 28006,28007,28008.....28012...). On s4 restart it still does not get reset -> 28016 (my current) .. is already at 28021.."

**Comment by wtfblub** [comment]
He clearly doesn't know how it works because that's exactly what it should do.
