### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by ouchadam** [wtfblub/NetspherePirates#146]
first of all, thanks for creating this!

Is there any documentation (other than the code itself 😄 ) about the architecture/network stack or any Charles/wireshark responses etc?

**Comment by wtfblub** [comment]
http://guide.nettention.com/cpp_en

This version of S4 League uses outdated version of proudnet but the basic concept is the same.

**Comment by ouchadam** [comment]
perfect, consider this solved
