### ISSUE TITLE
DotNetty.Codecs.DecoderException

### ISSUE THREAD

**Issue by iBreak97** [wtfblub/NetspherePirates#155]
This error occurred when i am the master of room. After few minutes, server kick me.

[DotNetty.Codecs.DecoderException.txt](https://github.com/wtfblub/NetspherePirates/files/916139/DotNetty.Codecs.DecoderException.txt)

**Comment by BioAleks** [comment]
https://github.com/wtfblub/NetspherePirates/issues/165
Have too problem with decoder.
But my friend be kicked, not i (i host or he - it does not matter).
