### ISSUE TITLE
[branch 1184] How to launch the Client?

### ISSUE THREAD

**Issue by Shinzuyakun** [wtfblub/NetspherePirates#156]
Well, I have the 1184 Client ready but how to launch it without loading xtrap (+ hgwc)?

**Comment by FreeDenny9700** [comment]
You must remove TheMida from client and by-pass xtrap and hgwc open. It's not very simple to do. Good luck

**Comment by wtfblub** [comment]
https://mega.nz/#!WVs2nTTQ!PIGIXSyE5VpnOswWiuAQ1zenylb3tLrZR3CAfQyNFnk

**Comment by FreeDenny9700** [comment]
Uh thanks you Wtfblub

**Comment by GameRaiderLP** [comment]
well you cannot use the 1184 branch currently

**Comment by FreeDenny9700** [comment]
Why?

**Comment by GameRaiderCC** [comment]
its not ready

**Comment by FreeDenny9700** [comment]
Ah ok, thanks

**Comment by XXXTEMPTATION** [comment]
@Shinzuyakun where can I get the 1184 client?

**Comment by Shinzuyakun** [comment]
by patching it by yourself

**Comment by Shinzuyakun** [comment]
@wtfblub if i try to launch the game via start.bat it crashes for me.
Is my client maybe wrong? My latest resource in _resources folder is 25.02.2013

**Comment by FreeDenny9700** [comment]
Update Season 1 (Patch 1126) Client with official patcher to patch 1184, insert Blub files and start client with .Bat

Note: if you want use official S4 League Patcher, you must modify version.dat otherwise updater doesn't work

**Comment by GameRaiderCC** [comment]
Well Patch 26 isbt 1126.
Well just find a old client(example: 2012)
And patch it to 1184 (change localinfo.dat to your own 0815 webserver with a Version.ini and latest=1184)

**Comment by FreeDenny9700** [comment]
For me: i have get my Version.dat from original client (patch 1350) and i have modify this value to 1126. After, i put on Season 1 client directory the original S4 League patcher to patch game to 1184. It work very well for me.
You can edit Version.dat, this is a simple binary file.

**Comment by Shinzuyakun** [comment]
I already got it working ^^

**Comment by Mr-Sp1x3r** [comment]
@GameRaiderCC You Said Packets And Handlers&Structs and the emulator for the 1184 branch in general are not Ready,So Why Wtfblub made some commits Fixing Everything but he did errors and he didnt fix Them??

**Comment by P1Youssef** [comment]
how does it works anyway ? i changed the localinfo.dat links to my own version.ini ( changed latestversion to 1184) on my own website and i checked if it works << it does work> but when i open the patcher it self updating and it changes to the aeria games patcher and changing localinfo doesnt work anymore... anyone know what did i do wrong ? or can someone send me the client  ? Thanks
