### ISSUE TITLE
Cannot get friend to connect

### ISSUE THREAD

**Issue by rzvwolf** [wtfblub/NetspherePirates#159]
Hey!
I ran into your files and I must say that I love this. Now, me and a friend are trying it out, and I can't get him to connect. I opened some ports, (28002 - 28005 and 27000, 80 also) but still nothing. Whenever I try and change an IP from 127.0.0.1/localhost in auth/game.json the .exes stop running. 
What must I do to get him play with me? Are there some ports I left unopened?
Oh, and btw, we're using the pre-built package.

**Comment by BioAleks** [comment]
You extract and export "data" folder to game server?

**Comment by rzvwolf** [comment]
Yes, I did that too. I can connect on the server and play, but I my friend cannot. I tried, as I said, to open ports, change IPs and nothing has worked.

**Comment by BioAleks** [comment]
"IP from 127.0.0.1/localhost in"
You use ip like 192.168.x.x?

**Comment by rzvwolf** [comment]
Well, I gave him the global IP to connect to and I tried leaving 127.0.0.1/localhost into the setting files. Should I use the local IP like the one you used as example, so my friend can connect to the game with the global one?

**Comment by BioAleks** [comment]
If you no need connection from global internet - you use 127.0.0.1.
If need - you use your local PC computer (you can change your pc local ip in your router).
For connection from other pc you/your friends/etc need to use your internet IP.
http://myip.ru

And add to desktop file settings parameter with ip your internet ip.

**Comment by GameRaiderCC** [comment]
You can also directly use your Global ip
