### ISSUE TITLE
Server doesn't show up

### ISSUE THREAD

**Issue by Ezelmontage** [wtfblub/NetspherePirates#160]
When starting the Game.exe it gives me an error.
It says "Failed to update serverlist"

[debug_2017-04-22 - .txt](https://github.com/wtfblub/NetspherePirates/files/949262/debug_2017-04-22.-.txt)

![s4client](https://cloud.githubusercontent.com/assets/27901230/25308016/47063cfa-27ac-11e7-949e-adbdeba56b6b.png)

**Comment by BioAleks** [comment]
Try to use your local PC ip.
