### ISSUE TITLE
1184 Emulator Stat

### ISSUE THREAD

**Issue by Mr-Sp1x3r** [wtfblub/NetspherePirates#161]
Hello Blub!
What if i got my client patched 
What i should do exactly to use it please help me and tell me if i can login and play some matchs in the 1184 client !
and what i can do with the actual 1184 emulator

**Comment by GameRaiderCC** [comment]
The 1184 emulator is not ready yet.

**Comment by BioAleks** [comment]
You need to reprogram this emulator for this client.

**Comment by Mr-Sp1x3r** [comment]
i mean if i used it and ran the client will it login correctly and connect to server or ?

**Comment by GameRaiderCC** [comment]
no it doesnt

**Comment by Mr-Sp1x3r** [comment]
Hopefully blub work on the 1184 Emulator better than wasting his time with the season 1 its useless. i think a full season 4 emulator will be extremly good

**Comment by BioAleks** [comment]
Blub no waste time because reprogram easy than program new from nothing.

**Comment by Demon0no** [comment]
There are some people here who like the older versions of s4 more than the newer ones (I'm one of them). Working on the season 1 emulator definitely is NOT wasted time, even if you're not interested in it. Having a good code-base for one makes it easier to translate the emulator to other s4 versions. Like BioAleks already said you should be a bit more thankfull towards wtfblub, as without him and his research in the network structure there'd be no emulator at all.

**Comment by FreeDenny9700** [comment]
Quote BioAleks and Demon0no. Thanks you so much Wtfblub, your work is very important for us

**Comment by Mr-Sp1x3r** [comment]
i appreciate the hard work of wtfblub in his emulator but i just gave me opinion about the season1 emulator 
So Be sure to read my last comment before Writing that kind of answers and 
love you wtfblub ! <3

**Comment by GameRaiderCC** [comment]
You can also update it by yourself.
Here some pics of my old(season1-2) projects and pictures of season3-5 i've done with the last commits of blub. 
![season2](https://cloud.githubusercontent.com/assets/21315274/25430519/3ef60148-2a7d-11e7-934b-6ed19bae42f9.jpg)
![season3](https://cloud.githubusercontent.com/assets/21315274/25430515/3ef080ec-2a7d-11e7-85ed-0ea30cbea38e.jpg)
![season4](https://cloud.githubusercontent.com/assets/21315274/25430518/3ef4e3da-2a7d-11e7-8254-81b588326a15.jpg)
![season5](https://cloud.githubusercontent.com/assets/21315274/25430520/3ef6c92a-2a7d-11e7-8f56-ff8d92eb1cca.jpg)
![season1](https://cloud.githubusercontent.com/assets/21315274/25430517/3ef2fe76-2a7d-11e7-88b8-83699fca4d43.jpg)

**Comment by Mr-Sp1x3r** [comment]
Please help me i want a server like this please 
this is how you can contact me : https://web.facebook.com/Leaguer123
i hope you tell me what update number is this and how to make at least able to play with like the last screen

**Comment by BioAleks** [comment]
#closerequest

**Comment by Mr-Sp1x3r** [comment]
Why ?

**Comment by GameRaiderCC** [comment]
The version i've used:
Season 1: 1140/1144
Season 2: 1145
Seaaon 3: 1174
Season 4: 1184
Season 5: 1192

**Comment by Mr-Sp1x3r** [comment]
i Truly love you Bro! Thanks for everything

**Comment by s4archivos** [comment]
@GameRaiderCC HOW CAN I UPDATE SEASON 4.

YOU MIGHT PASS THE CLASS SEASON 5 OR 4. PLEASE
