### ISSUE TITLE
Hamachi IP Its not Working

### ISSUE THREAD

**Issue by Mr-Sp1x3r** [wtfblub/NetspherePirates#163]
Hello Guys!
When i tried to Play With my friend in the server using the hamachi IP
I Set everything in the Auth.hjson And Game.hjson Both Emulators Closed With the following Log:
2017-04-30 09:00:00.2733|INFO|AuthDatabase:109|Initializing... 
2017-04-30 09:00:00.6122|INFO|Program:39|Starting server... 
2017-04-30 09:00:01.0194|ERROR|Program:97|UnhandledException 
System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.Net.Sockets.SocketException: L’adresse demandée n’est pas valide dans son contexte
   à System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   à System.Net.Sockets.Socket.Bind(EndPoint localEP)
   à DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.DoBind(EndPoint localAddress)
   à DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BindAsync(EndPoint localAddress)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à DotNetty.Transport.Bootstrapping.AbstractBootstrap`2.<DoBindAsync>d__26.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Threading.Tasks.TaskExtensions.WaitEx[TResult](Task`1 this)
   à ProudNet.ProudServer.Listen(IPEndPoint tcpListener, IPAddress udpAddress, Int32[] udpListenerPorts, IEventLoopGroup listenerEventLoopGroup, IEventLoopGroup workerEventLoopGroup) dans C:\projects\netspherepirates\src\ProudNet\ProudServer.cs:ligne 105
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.ExceptionExtensions.Rethrow(Exception this)
   à ProudNet.ProudServer.Listen(IPEndPoint tcpListener, IPAddress udpAddress, Int32[] udpListenerPorts, IEventLoopGroup listenerEventLoopGroup, IEventLoopGroup workerEventLoopGroup) dans C:\projects\netspherepirates\src\ProudNet\ProudServer.cs:ligne 153
   à Netsphere.Program.Main() dans C:\projects\netspherepirates\src\Auth\Program.cs:ligne 42
---> (Exception interne #0) System.Net.Sockets.SocketException (0x80004005): L’adresse demandée n’est pas valide dans son contexte
   à System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   à System.Net.Sockets.Socket.Bind(EndPoint localEP)
   à DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.DoBind(EndPoint localAddress)
   à DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BindAsync(EndPoint localAddress)<---

**Comment by GameRaiderCC** [comment]
Just do not use Hamachi

**Comment by Mr-Sp1x3r** [comment]
But i want to play with my friends
PS: i haven't A Router iam using USB Internet Key
