### ISSUE TITLE
Less bugs if local hosted

### ISSUE THREAD

**Issue by GameRaiderCC** [wtfblub/NetspherePirates#166]
Just want to note that the emu has less bugs if it gets hosted in a local network(not only localhost).

Example 1: P2P (2 clients same pc/address, 2 clients 2 different pcs) (in combination with #167)
Local Server: p2p connection works(yeah, no firewall)
Global Server: no p2p connection
Global Server + 2 Clients from same network gets fixed if ServerHandler.cs:65 gets changed:
`if (stateA.HolepunchSuccess && stateB.HolepunchSuccess) ` -> `if (stateA.HolepunchSuccess)`

Example 2: Roomjoin (known issue)
Local Server: No stuck at join(emtpy room, bugged start/ready)
Global Server: Randomly stuck and players needs to rejoin multiple times until it works (Joinmessage gets dropped cuz of a rule)

**Comment by GameRaiderCC** [comment]
Example 1: found a fix
Example 2: a weird timing issue, I've removed the rule is connecting==true which has caused this bug

**Comment by BioAleks** [comment]
You can use "Pull Requests" for help.
