### ISSUE TITLE
P2P - Notes

### ISSUE THREAD

**Issue by GameRaiderCC** [wtfblub/NetspherePirates#167]
Debugged some peer2peer stuff and saw:

ServerHandler.cs:42(NotifyP2PHolepunchSuccess)
    Local test: stateA succeeds 2 times --> p2p(not behind firewall)
    Global test: stateA succeeds 1 time --> no p2p(clients behind nat)
        -> only stateA succeeds, stateB never does.
        -> `if (stateA.HolepunchSuccess && stateB.HolepunchSuccess)` always false

ServerHandler.cs:88(NotifyJitDirectP2PTriggered)
    -> stateA gets triggered 2 times, stateB never
    -> `if (stateA.JitTriggered && stateB.JitTriggered)` always false

--> Does Holepunch itself dont work? Wrong Endpoints set?

**Comment by wtfblub** [comment]
This is being tracked in #3
