### ISSUE TITLE
Last Message To Blub

### ISSUE THREAD

**Issue by Mr-Sp1x3r** [wtfblub/NetspherePirates#168]
i Know its Not The Righ way to Post this But
You know S4 League Is Still Dying And All The Community is depending on you So Please
Keep Working on the 1184 Patch From time to time And maybe Surpass it by Developing a Season 6 Emulator 
i Know its not easy But Great Thing takes time
Thanks

**Comment by BioAleks** [comment]
He is working from time to time.
And has real life. So, wait. Have patience or help too.

**Comment by Mr-Sp1x3r** [comment]
Thanks For the reply!
