### ISSUE TITLE
Patch 1139 Client 

### ISSUE THREAD

**Issue by Mr-Sp1x3r** [wtfblub/NetspherePirates#171]
Hey Netsphere Pirates Community!
If anyone here have The patch 1139 Bypassed Client with its arguments please share it here i truly need it

**Comment by Mr-Sp1x3r** [comment]
@wtfblub Do you have it?

**Comment by GameRaiderCC** [comment]
why do you need the 1139 client?

**Comment by Mr-Sp1x3r** [comment]
@GameRaiderCC Answer me in Discord --"

**Comment by Mr-Sp1x3r** [comment]
@GameRaiderCC Then Can you give me The 1141 Client?
