### ISSUE TITLE
No channel, how do I fix it? Patch 1184

### ISSUE THREAD

**Issue by foantom00** [wtfblub/NetspherePirates#176]
@GameRaiderCC
Help me please
this is how you can contact me FB: https://www.facebook.com/Stanscall
i hope you tell me
![s4_20170525_222302](https://cloud.githubusercontent.com/assets/9758492/26456921/bdabcc8e-4198-11e7-9052-63d9e5c464c0.jpg)

**Comment by GameRaiderCC** [comment]
wat

**Comment by foantom00** [comment]
Absoluut niet

**Comment by foantom00** [comment]
Hoe los ik dit op?

**Comment by Zandrox** [comment]
This is weird, @foantom00 you are speaking Dutch?
