### ISSUE TITLE
How i can update client 1184?

### ISSUE THREAD

**Issue by s4archivos** [wtfblub/NetspherePirates#177]
Please help!

**Comment by Mr-Sp1x3r** [comment]
So When it comes to getting a 1184 Patch (Season 4) Client You have to : 
1)Download a Client older than 1184 ( http://bit.ly/2reQKgP ) recommended
2) Install The Game Then Go to the client path mentionned while setting the installer
3) Run Patcher.exe and let your game patching
4) Once the game finish the update 1184F.cab and start patching in 1185D.cab Close The patcher
5) Download The Patched Client.exe & Run Command (http://bit.ly/2rNOe1K) recommended
6)Open start.bat and Enjoy ^_^

When you need any help feel free to contact Me On My Facebook : http://bit.ly/2qrgCXL
