### ISSUE TITLE
Season 4 Channels Bug

### ISSUE THREAD

**Issue by Mr-Sp1x3r** [wtfblub/NetspherePirates#178]
Yoow Guys Whats up !
After Fixing The Last 1184 Patch Blub Commit I started working on channels
I Got This Bug After Updating The Channel Logic &  Xml Structure
Any Help or information About what causing this or the file which responsible for that 
Also i wanted to ask if anyone wants that i fork the blub's Project and update & share for public?
And Thanks ^_^
![ejwvzmenwyamambdgaahjabng0qqqqoxaudvdfe033vcrz3zurs6rcbaay62ms9dl-gzatgvuv4ljbz05g5jjowzl1swodhkiyjbditrw_ejiir28zz4f8maak3_m3fx9x0bwv8h4a](https://cloud.githubusercontent.com/assets/27924725/26548040/51da648e-4472-11e7-84c2-8fe8c9759bc4.png)

**Comment by GameRaiderCC** [comment]
Wrong struct

**Comment by Mr-Sp1x3r** [comment]
@GameRaiderCC Which files to edit exactly
