### ISSUE TITLE
Is it possible to separate PEN and AP from store items?

### ISSUE THREAD

**Issue by herguet** [wtfblub/NetspherePirates#183]

**Comment by s4archivos** [comment]
Yes, just create a new price group of type 2 and you can seperate the ap and pen

**Comment by herguet** [comment]
How would I do that, I do not even know where to start

**Comment by herguet** [comment]
How can I add values ​​in items and to put after I have to create other tables?

**Comment by s4archivos** [comment]
You can separate the ap from the pen, in the table that says shop_prices and add the value id: 2, 2

**Comment by herguet** [comment]
Where do I put the value for each item?

**Comment by HARUWEEN** [comment]
You have way too many questions man, this is a DIY thing, people will help you but we can't spoonfeed you, you will need to know the basics in order to keep up with this community, it's a better idea to just drop it and stick to the original s4

**Comment by gabrielpop12** [comment]
I added the ID to the AP, the PEN value also changed, but when I reboot the server and everything, no change occurs
