### ISSUE TITLE
Empty Shop

### ISSUE THREAD

**Issue by mrmobd3** [wtfblub/NetspherePirates#185]
How To Fix It
![s4_20170531_220423](https://user-images.githubusercontent.com/29818387/27763253-37470aa0-5e80-11e7-81e3-22f0ae979f3d.jpg)

**Comment by GameRaiderCC** [comment]
don't ask for 1184 fixes

**Comment by Mr-Sp1x3r** [comment]
Ya Ahmed ana Rabi3 lw 3ayez Fix t3ala Private
https://www.facebook.com/leaguer123
