### ISSUE TITLE
Error Please Help

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#187]
Now I am trying to extract data from season 4 1184 client
what to do to start this client with the server ?
![untitled](https://user-images.githubusercontent.com/21015911/27846126-c4208e82-613d-11e7-9f68-6c0bcb1438f2.png)

**Comment by redapro** [comment]
Here is is another extractor

**Comment by Demon0no** [comment]
1. This is an issue tracker, not a support forum  
2. Branch 1184 is a testing branch and noone is supposed to open issues for it in the first place
