### ISSUE TITLE
Important !Really Important

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#194]
How to Decrypt The account password?
How does it wotk with salt?

**Comment by Mr-Sp1x3r** [comment]
Figure out how everything is working
none give a shit about helping you in something you can help yourself with

**Comment by Demon0no** [comment]
The password is hashed and salted. There is no way to decrypt it. If you wanted to know how to generate passwords yourself, look into the PBKDF2 key stretching algorithmus. We use SHA1 with a difficulty of 24000. The result is saved as base64.
You can look at the implementation here: https://github.com/wtfblub/NetspherePirates/pull/148/files

**Comment by redapro** [comment]
yup demon i know all that and i know its sha1 combined with salt...i only need a method for decrypting

**Comment by Demon0no** [comment]
There is none, you'd have to try brute forcing it.

**Comment by gabrielpop12** [comment]
Why do you want to know the password?
If it is yours you will know the password, if you open a server with the files better not know the password. There is a method, but there are places that do that.
