### ISSUE TITLE
How do I setup all of this?

### ISSUE THREAD

**Issue by Feeyz** [wtfblub/NetspherePirates#207]
How do I get this stuff running properly? I compiled it and got my two application dll files Auth and Game. I've put the whole directory on my VPS and tried to run it but its always saying it's missing some dependencies in a /lib/ directory that does not even exist. Altough there is one called "libs" in the root directory but it does not matter because these librarys are still missing inside it.

What do I have to look for to get this emulator running? Some changes in Code maybe?

**Comment by Demon0no** [comment]
1. Install requirements
2. "git clone https://github.com/wtfblub/NetspherePirates"
3. Setup databases
4. "dotnet restore"
5. cd into Auth directory
6. "dotnet run" to generate a config
7. Edit the auth.hjson
8. "dotnet run" again to start the server
9. Repeat steps 5-8 for the game server
10. ????
11. Profit
