### ISSUE TITLE
How To Start .NEt Core Versions ?

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#210]
I Have Built .Net Core source but i cannot find Auth.exe or even .hjson
How Can I open them (Master - Patch 1139 ) ?

**Comment by wtfblub** [comment]
`dotnet exec path/to/Auth.dll` and `dotnet exec path/to/Game.dll`

**Comment by redapro** [comment]
Can You Explain More Please?
I am a C# - Python Programmer but i didn't read your source ..so , i am not familiar with it

**Comment by redapro** [comment]
I Have Opened My laptop Now...I am So Sorry...I Will open dotnet console and open it..just i didn't read the comment clearly from my android

**Comment by redapro** [comment]
Error:
  An assembly specified in the application dependencies manifest (Auth.deps.json
) was not found:
    package: 'BlubLib.DotNetty.SimpleRmi', version: '0.1.4'
    path: 'lib/netstandard2.0/BlubLib.DotNetty.SimpleRmi.dll'
I get This error

**Comment by BioAleks** [comment]
Same for me

**Comment by wtfblub** [comment]
Are you using the binaries from the build server? If yes download the latest ones, i fixed the build process.

If you are compiling yourself: Make sure to run `dotnet restore` and then `dotnet build`(`dotnet publish` if you plan on running the server on another machine) then you can just run it as explained above.

or you can run the server directly from the source with `dotnet run --project src/Auth` or `dotnet run --project src/Game`

**Comment by redapro** [comment]
Thanks Compiling Method Fixed 👍

**Comment by BioAleks** [comment]
Thx. With new fix it's working.
