### ISSUE TITLE
Error When Trying To Open Project In VS 2015 & VS 2017

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#213]
Projects Aren't Loading With An Error.
Here is the output:
C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\ProudNet\ProudNet.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\ProudNet\ProudNet.csproj

C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Netsphere\Netsphere.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Netsphere\Netsphere.csproj

C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Netsphere.Network\Netsphere.Network.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Netsphere.Network\Netsphere.Network.csproj

C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Netsphere.Database\Netsphere.Database.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Netsphere.Database\Netsphere.Database.csproj

C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Auth\Auth.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Auth\Auth.csproj

C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Game\Game.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Game\Game.csproj

C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Netsphere.Resource\Netsphere.Resource.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Netsphere.Resource\Netsphere.Resource.csproj

C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\tools\DataExtractor\DataExtractor.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\tools\DataExtractor\DataExtractor.csproj

C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Auth.ServiceModel\Auth.ServiceModel.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\Auth.ServiceModel\Auth.ServiceModel.csproj

C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\tools\NetsphereExplorer\NetsphereExplorer.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Unkown\Downloads\NetspherePirates-master\NetspherePirates-master\src\tools\NetsphereExplorer\NetsphereExplorer.csproj

**Comment by Demon0no** [comment]
You need Visual Studio 2017 Update 3.
The versions before that don't support .Net Core 2.0

**Comment by BioAleks** [comment]
15.2 Build 26430.6 version need? 
Or what version?
Blub no update info.

**Comment by GameRaiderCC** [comment]
Install the .Net (Core) SDK

**Comment by redapro** [comment]
Already Installed All Of These
Same Error!

**Comment by BioAleks** [comment]
Yes, already installed.
Same.

**Comment by Mellowz** [comment]
install .net framework 4.6.1 also

**Comment by BioAleks** [comment]
Omg, seriously.
Stop say "install this, install this".
All installed.

**Comment by GameRaiderCC** [comment]
Then: www.google.com

**Comment by wtfblub** [comment]
You need Visual Studio 2017 Version 15.3 and .Net Core 2 SDK(and Net Framework 4.6.1 if you want to compile and run the tools)

**Comment by redapro** [comment]
Fixed By Downloading Latest Source 👍 Thanks

**Comment by BioAleks** [comment]
15.3 VS Working. Thx
