### ISSUE TITLE
Netsphere Editor Problem

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#215]
When ever I Replace xml Files either the game doesn't start..or starts and immediately closes!€
Even if i extracted it's own xml and replaces.Also,Doesn't Start
Netsphere Editor Was Working In Old Source Version(Patch26)

**Comment by BioAleks** [comment]
Are you use new editor?

**Comment by redapro** [comment]
Yes the newest editor!
Try To Replace Weapon.x7 or any file in xml folder

**Comment by redapro** [comment]
@wtfblub

**Comment by redapro** [comment]
Same Problem
