### ISSUE TITLE
I need GameRaider CC for a help

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#218]
I need you for something privately..
Should you talk to me using discord , facebook or what?

Remark This as a Question ..I'm Sorry Blub :)
What's The Difference Between Patch 26 and This Patch?

**Comment by BioAleks** [comment]
This patch - 34. Last before new interface in S4.
You can read pathnotes here: http://web.archive.org/web/20170728180513/https://forums.s4project.net/topic/12332-s4-league-patch-guide-1-67
In this client Breaker working and "Shockwave Gun" (maybe you don't know what is this, but old players know). Other changes - read.

**Comment by redapro** [comment]
@BioAleks Thanks  but I Know All Of This..I only have put a question  to not make an empty issue

**Comment by GameRaiderCC** [comment]
what?

**Comment by Hanakoizumi** [comment]
congrats game, you're famous now

**Comment by redapro** [comment]
@GameRaiderCC Accept me in discord     4LPH4#7276
