### ISSUE TITLE
Disconnect when play

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#219]
[dropbug.txt](https://github.com/wtfblub/NetspherePirates/files/1307008/dropbug.txt)
Hello.
We play in Touch Down. 
When i kill friend with dagger - server drop him to server change.

P.S. UDP enabled.

**Comment by BioAleks** [comment]
Is this error like this? https://github.com/wtfblub/NetspherePirates/issues/155
But error message different

**Comment by iBreak97** [comment]
i have fixed this error myself
