### ISSUE TITLE
Add/Replace x7 files

### ISSUE THREAD

**Issue by FreeDenny9700** [wtfblub/NetspherePirates#22]
Your library Netsphere.Resources not work when user add or replace x7 files on ResourceTool. All files Can be added or replaced but x7 files no

**Comment by BioAleks** [comment]
How about x4?

**Comment by FreeDenny9700** [comment]
X4 files?? What?? In this season there are X7 Files. You can download from my repo an ResourceTool created by Blub libs and test this

**Comment by BioAleks** [comment]
I know without your resource tool because I unpack all client by using blub extractor. 
Your resource tool very-very slow. And add folders tree. Waiting for change 1 file and try to search it without folders? Are you kidding me?

**Comment by FreeDenny9700** [comment]
yes, it is a shitty tool but for now it work. in future i update this

**Comment by Vyre** [comment]
I also tried replacing x7 files in the past, but appearently it didn't encrypt it properly and the client ended up crashing on start with no error message whatsoever.

Since decrypting works perfectly fine, I have no idea why it doesn't encrypt properly.

**Comment by shanzenos** [comment]
"I know without your resource tool because I unpack all client by using blub extractor." To my knowledge blub doesn't have a season 1 resource tool released, what are you referring to?

**Comment by shanzenos** [comment]
Having the same issue as Vyre. Though you can add new files just fine, if you try replacing or deleting & re-adding existing files the client won't even load anymore.

**Comment by BioAleks** [comment]
Error is:  CCryptFile::Open::if( unbufferedReadFile.Open( szCRC), OPENMODE_READ ) ) in starting client.

**Comment by BioAleks** [comment]
I see. I try use old resource for game (arcade item.x7 for example).
What result? Game say need file "e2f3a5e09dbcb28f". I copy it. Game working. So... tool change files?

**Comment by Vyre** [comment]
What are you talking about? You need to use the Save function otherwise it won't modify the s4hd.

**Comment by FreeDenny9700** [comment]
ResourceTool creates new file and replace it on Resource.S4HD. your game work because when you replace new s4hd file with old s4hd file, old s4hd file refers to old file (not delete) into _resources

**Comment by BioAleks** [comment]
"What are you talking about? You need to use the Save function otherwise it won't modify the s4hd."
What about you talking? Are you kidding me? LoL. I know.

"ResourceTool creates new file and replace it on Resource.S4HD. your game work because when you replace new s4hd file with old s4hd file, old s4hd file refers to old file (not delete) into _resources"
I no replace .s4hd, i add only old file to _resources

**Comment by FreeDenny9700** [comment]
better explained and consider what we said

**Comment by BioAleks** [comment]
I know what you said, but after some working with tool - tool die. Error. No working.

**Comment by FreeDenny9700** [comment]
Old file exist into _resources, it is impossible... Tomorrow i test it

**Comment by FreeDenny9700** [comment]
which tool you are using ?

**Comment by BioAleks** [comment]
In your git PreBuild Package "ResTool.zip"

**Comment by FreeDenny9700** [comment]
Ok, it work perfectly for me, replace function work with other file but for x7 file no. It's unique error

**Comment by Vyre** [comment]
> What about you talking? Are you kidding me? LoL. I know.

Considering google translate does a better job at english than you, from what I read I thought you replaced the resources and didn't save the s4hd. I actually still think that that's what you're doing so no, I am not kidding you.

**Comment by FreeDenny9700** [comment]
I replace scn of Spy dagger with scn of new mach3 and add .dds texture to model directory. It work very well for me. Tool work fine but x7 file is corrupt

**Comment by BioAleks** [comment]
No waste time for you.

FreeDenny9700, 
х7 too no working for me. For all. 
About that I say (tool error). Now i can't use "save". Add error
[savedebug.txt](https://github.com/wtfblub/NetspherePirates/files/372477/savedebug.txt)

**Comment by Vyre** [comment]
> I replace scn of Spy dagger with scn of new mach3 and add .dds texture to model directory. It work very well for me. Tool work fine but x7 file is corrupt

Everything except x7 is indeed working.
I am not using your resource tool, but I also could replace the scns & dds files and it worked.

You gotta keep in mind that encrypting x7 files does not work the same way that it does for the rest (except lua).

Just weird since decrypting works fine, encrypting should be the same just the other way around.

If I can recall properly, my last guess was that the BuildX7 function was broken. Maybe we're just doing it wrong tho.

**Comment by FreeDenny9700** [comment]
Oh. Try download my source code and compile this. Try with your .exe file (remember that you must intert all library into debug folder) 
Tomorrow i see this, thanks for report error bro

**Comment by FreeDenny9700** [comment]
It is not just the opposite because at the original files they are Removed to x7 files few bytes that will not be more inserted . but this should not be a problem

**Comment by BioAleks** [comment]
FreeDenny9700, nothing for, but i use .zip because when i try to compile it say "error when try to complete task Fody.WeavingTask"

**Comment by FreeDenny9700** [comment]
Oh, tomorrow i update source for remove this package that give you error

**Comment by BioAleks** [comment]
Okay.

Compile source = "error when try to complete task "Fody.WeavingTask".
As you say - all files (library) in.

**Comment by FreeDenny9700** [comment]
Source have all addictions to my computer. Tomorrow i delete it. Sorry for problem, i'm not very good in C#

**Comment by FreeDenny9700** [comment]
Try to remove costura32/costura64 folder and remove FodyWeavers.xml and try to compile it. Remember that you must move all library to Debug folder (library is in /libs)

**Comment by BioAleks** [comment]
FreeDenny9700, it's just be "file costura32\Netsphere.Resource.dll" not found.

**Comment by BioAleks** [comment]
FreeDenny9700, it's just that "error when try to complete task "Fody.WeavingTask".

**Comment by FreeDenny9700** [comment]
Add BlubLib.dll and Netsphere.Resources as Resources

**Comment by wtfblub** [comment]
Move the discussion about his tool to his repo please. I'll look into this issue when i'm done with the new resource tool, probably just a typo somewhere.

**Comment by wtfblub** [comment]
Fixed by #02280831d4cf0bb8e7b7c6591bfcea39c2cf51ae
