### ISSUE TITLE
SAME Netsphere Editor Problem

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#223]
![untitled](https://user-images.githubusercontent.com/21015911/30498019-724de2de-9a55-11e7-998e-ddc40b49e2fb.png)

**Comment by wtfblub** [comment]
Works fine for me. Any more info please?

**Comment by redapro** [comment]
@wtfblub For example i added asassin dagger files  .Then i put info in .x7 files
I Replace x7 files ..Try to open the game nothing happen
Try to start the "start.bat" as admin a message pops up says "Windows cannot find S4Client.exe"
Btw S4Client and all files are in same place with same name
Start.bat commands :
start S4Client.exe -rc:eu -lac:eng -auth_server_ip:127.0.0.1

**Comment by wtfblub** [comment]
Don't start the .bat file as admin.

**Comment by redapro** [comment]
@wtfblub  I said i started it with both
Open and tried as admin with no respone from the client !
Tried extracting the .x7 files and replacing again same and Also same problem.....
This is not a Question

**Comment by BioAleks** [comment]
For me all ok too.

**Comment by BioAleks** [comment]
Yes, some .x7 files create problems.
For me client no open. Nothing happened.

I change language x7 files working and client work. 
I change x7 files in xml folder and client no start.

**Comment by BioAleks** [comment]
@wtfblub 
Yes, some .x7 files create problems.
For me client no open. Nothing happened.

I change language x7 files and client work.
I change x7 files in xml folder and client no start.

**Comment by redapro** [comment]
@BioAleks  exactly!

**Comment by BioAleks** [comment]
I have client copy (that i no edit with resource tool).
Try to replace all files that i change. 
Result: client no start.

**Comment by redapro** [comment]
@wtfblub

**Comment by BioAleks** [comment]
It's working ok now.
