### ISSUE TITLE
Question: .exe files?

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#227]
Hello @wtfblub .
You create .exe files for server or no (for start server)?

Yes, no problem to do this by self or start server if use windows cmd.
Just interesting.

**Comment by rzvwolf** [comment]
Download the source files and compile them in Visual Studio?

**Comment by redapro** [comment]
You Can Do It Yourself..
By a .bat file or a self-made .exe using C#...Should I Upload Mine?

**Comment by wtfblub** [comment]
You can build your own exe files with `dotnet publish -r system` with the latest source. Replace system with one of the following values:
- win-x86
- win-x64
- linux-x64

Output is in `bin\Debug\netcoreapp2.0\system\publish`

**Comment by BioAleks** [comment]
ok, thx

**Comment by enriquesito5** [comment]
Can you tell me what to put in the bat file to run game and auth

**Comment by iBreak97** [comment]
dotnet Auth.dll for start Auth server
dotnet Game.dll for start Game server

**Comment by enriquesito5** [comment]
I get error

**Comment by enriquesito5** [comment]
![game](https://user-images.githubusercontent.com/33380045/32987158-c17fe7c0-ccb0-11e7-9d74-36cc2866ec10.jpg)

**Comment by Demon0no** [comment]
1. That error has nothing to do with this issue.
2. Do you have a mysql server running and configured in the auth and game server?

**Comment by enriquesito5** [comment]
Data Base
![data base](https://user-images.githubusercontent.com/33380045/32993081-49ef4112-cd21-11e7-9e78-1a74bed3b118.jpg)
error Auth
![auth](https://user-images.githubusercontent.com/33380045/32993082-4a1934a4-cd21-11e7-9db1-ef898bccfff4.jpg)

Error Game
![game](https://user-images.githubusercontent.com/33380045/32993083-4a3f3302-cd21-11e7-96aa-60940268f2dd.jpg)

**Comment by Demon0no** [comment]
Post your Auth.hjson and Game.hjson.

**Comment by enriquesito5** [comment]
Auth.hjson
{
  listener: 127.0.0.1:28002
  max_connections: 100
  api:
  {
    listener: 127.0.0.1:27000
    serverlist_timeout: 30000
  }
  noob_mode: true
  auto_register: true
  database:
  {
    auth:
    {
      host: localhost
      port: 3306
      username: root
      password: 
      database: auth
      run_migration: false
    }
  }
}

**Comment by enriquesito5** [comment]
Game.hjson
{
  server_name: Netsphere
  server_id: 1
  server_ip: 127.0.0.1
  listener: 127.0.0.1:28003
  listener_chat: 127.0.0.1:28004
  listener_relay: 127.0.0.1:28005
  listener_relay_udp_ports: null
  listener_threads: 1
  worker_threads: 2
  player_limit: 100
  security_level: 0
  auth_webapi:
  {
    endpoint: 127.0.0.1:27000
    serverlist_update_interval: 25000
  }
  save_interval: 60000
  noob_mode: true
  database:
  {
    auth:
    {
      host: localhost
      port: 3306
      username: root
      password: 
      database: auth
      run_migration: false
    }
    game:
    {
      host: localhost
      port: 3306
      username: root
      password: 
      database: game
      run_migration: false
    }
  }
  game:
  {
    enable_tutorial: true
    enable_license_requirement: false
    max_level: 100
    start_level: 0
    start_pen: 10000
    start_ap: 10000
    start_coins1: 0
    start_coins2: 0
    durability_loss_per_death: 0
    durability_loss_per_minute: 0
    nick_restrictions:
    {
      min_length: 4
      max_length: 30
      max_repeat: 3
      allow_whitespace: false
      only_ascii: true
    }
    exp_rates_touchdown:
    {
      score_factor: 0.7
      first_place_bonus: 50
      second_place_bonus: 30
      third_place_bonus: 10
      player_count_factor: 0.06
      exp_per_min: 20
    }
    exp_rates_deathmatch:
    {
      score_factor: 0.7
      first_place_bonus: 50
      second_place_bonus: 30
      third_place_bonus: 10
      player_count_factor: 0.06
      exp_per_min: 20
    }
    exp_rates_chaser:
    {
      exp_per_first_point: 5
      exp_per_second_point: 3
      exp_per_third_point: 2
      score_factor: 0.7
      first_place_bonus: 50
      second_place_bonus: 30
      third_place_bonus: 10
      player_count_factor: 0.06
      exp_per_min: 20
    }
    exp_rates_battleroyal:
    {
      score_factor: 0.7
      first_place_bonus: 50
      second_place_bonus: 30
      third_place_bonus: 10
      player_count_factor: 0.06
      exp_per_min: 20
    }
    exp_rates_captain:
    {
      exp_per_first_point: 5
      exp_per_second_point: 3
      exp_per_third_point: 2
      score_factor: 0.7
      first_place_bonus: 50
      second_place_bonus: 30
      third_place_bonus: 10
      player_count_factor: 0.06
      exp_per_min: 20
    }
  }
}

**Comment by Demon0no** [comment]
I dont think empty passwords are supported, not sure though. You should make another database user (and only give it rights for the NetspherePirates databases) regardless, having a user for each "service" is an important practice imo.

**Comment by BioAleks** [comment]
Try enter IP in "host:"
No use localhost
