### ISSUE TITLE
Server patch 1184

### ISSUE THREAD

**Issue by Astiol** [wtfblub/NetspherePirates#228]
Hello, i am noob.
Can anyone explain to me how to use the MySQL server, since in the assembly that I have there is no exe file.
Are there any lessons?
The patch I use is: 1186
Server emulator : https://drive.google.com/file/d/0B8CSWTWBLtH5VDVtTUhfOGZYNHc/view

**Comment by redapro** [comment]
Don't Open Issues For 1184 Patch/Emulator
Request For Close
