### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Astiol** [wtfblub/NetspherePirates#229]
Tell me please, how can i fix this?

> ```
> 2017-09-18 06: 04: 16.0027 | INFO | Program-> Main: 0 || Checking database ...
> 2017-09-18 06: 04: 15.9182 | INFO | Program-> Main: 0 | Checking database ...
> 2017-09-18 06: 04: 15.9327 | INFO | Program-> Main: 0 | Starting server ...
> 2017-09-18 06: 04: 16.3953 | DEBUG | ProudServerPipe-> OnStart: 0 | Initializing ...
> 2017-09-18 06: 04: 17.5384 | INFO | Program-> Main: 0 || Starting server ...
> 2017-09-18 06: 04: 17.5914 | INFO | Program-> Main: 0 | Ready for connections!
> 2017-09-18 06: 04: 17.5914 | WARN | Program-> Main: 0 | AutoRegister is enabled. Accounts will be created for each new username received!
> 2017-09-18 06: 04: 18.1210 | DEBUG | ResourceCache-> GetChannels: 0 || Caching ...
> 2017-09-18 06: 04: 18.2930 | ERROR | Program-> OnUnhandledException: 0 || UnhandledException
> System.TypeInitializationException: The initializer of type "Netsphere.Network.GameServer" threw an exception. ---> System.InvalidOperationException: An error occurs in the XML document (1, 4). ---> System.Xml.XmlException: Unexpected XML declaration. The XML declaration must be the first node in the document, the use of space characters before it is not allowed., Line 1, position 4.
>    in System.Xml.XmlTextReaderImpl.Throw (Exception e)
>    in System.Xml.XmlTextReaderImpl.Throw (String res, String arg)
>    in System.Xml.XmlTextReaderImpl.ParsePI (StringBuilder piInDtdStringBuilder)
>    in System.Xml.XmlTextReaderImpl.ParseDocumentContent ()
>    in System.Xml.XmlTextReaderImpl.Read ()
>    in System.Xml.XmlTextReader.Read ()
>    in System.Xml.XmlReader.MoveToContent ()
>    in Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderChannelSettingDto.Read5_channel_setting ()
>    --- End of internal stack trace of exceptions ---
>    in System.Xml.Serialization.XmlSerializer.Deserialize (XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
>    in System.Xml.Serialization.XmlSerializer.Deserialize (TextReader textReader)
>    in Netsphere.Resource.ResourceLoader.Deserialize [T] (String fileName)
>    in the Netsphere.Resource.ResourceLoader. <LoadChannels> d__7.MoveNext ()
>    in System.Collections.Generic.List`1..ctor (IEnumerable`1 collection)
>    in System.Linq.Enumerable.ToList [TSource] (IEnumerable`1 source)
>    in Netsphere.Resource.ResourceCache.GetChannels ()
>    in Netsphere.Network.GameServer..ctor ()
>    in Netsphere.Network.GameServer..cctor ()
> --- End of internal stack trace of exceptions ---
>    in Netsphere.Network.GameServer.get_Instance ()
>    in Netsphere.Program.Main ()
> 2017-09-18 06: 05: 48.6474 | INFO | Program-> Main: 0 || Checking database ...
> 2017-09-18 06: 05: 49.7011 | INFO | Program-> Main: 0 || Starting server ...
> 2017-09-18 06: 05: 50.1820 | DEBUG | ResourceCache-> GetChannels: 0 || Caching ...
> 2017-09-18 06: 05: 50.2940 | ERROR | Program-> OnUnhandledException: 0 || UnhandledException
> System.TypeInitializationException: The initializer of type "Netsphere.Network.GameServer" threw an exception. ---> System.InvalidOperationException: An error occurs in the XML document (1, 4). ---> System.Xml.XmlException: Unexpected XML declaration. The XML declaration must be the first node in the document, the use of space characters before it is not allowed., Line 1, position 4.
>    in System.Xml.XmlTextReaderImpl.Throw (Exception e)
>    in System.Xml.XmlTextReaderImpl.Throw (String res, String arg)
>    in System.Xml.XmlTextReaderImpl.ParsePI (StringBuilder piInDtdStringBuilder)
>    in System.Xml.XmlTextReaderImpl.ParseDocumentContent ()
>    in System.Xml.XmlTextReaderImpl.Read ()
>    in System.Xml.XmlTextReader.Read ()
>    in System.Xml.XmlReader.MoveToContent ()
>    in Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderChannelSettingDto.Read5_channel_setting ()
> --- End of internal stack trace of exceptions ---
> in System.Xml.Serialization.XmlSerializer.Deserialize (XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
> in System.Xml.Serialization.XmlSerializer.Deserialize (TextReader textReader)
> in Netsphere.Resource.ResourceLoader.Deserialize [T] (String fileName)
> in the Netsphere.Resource.ResourceLoader. <LoadChannels> d__7.MoveNext ()
> in System.Collections.Generic.List`1..ctor (IEnumerable`1 collection)
> in System.Linq.Enumerable.ToList [TSource] (IEnumerable`1 source)
> in Netsphere.Resource.ResourceCache.GetChannels ()
> in Netsphere.Network.GameServer..ctor ()
> in Netsphere.Network.GameServer..cctor ()
> --- End of internal stack trace of exceptions ---
> in Netsphere.Network.GameServer.get_Instance ()
> in Netsphere.Program.Main ()
> ```

**Comment by iBreak97** [comment]
in Game Folder have you a "data" Folder? if you don't have this Folder, put Extractor into S4 Folder and run this. After move data Folder from S4 Folder to Game Folder

**Comment by Astiol** [comment]
I made new data folder using alice patch, want to make server for this patch)

**Comment by iBreak97** [comment]
Alice is only test server, not open request for this. Yes, i am Denny9700:)

**Comment by Astiol** [comment]
So this is impossible for me to make it ?
Unfortinally i am noob in this, but i'd like to learn)
