### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#230]
Maybe From 5 Months I Could Add Coupons To Player Using Auth / Game DB ..I Don't Remember but now i cannot find a coupon column,

**Comment by GameRaiderCC** [comment]
Coupons? these are items, not points

**Comment by redapro** [comment]
@GameRaiderCC  How to use or get them ? I 've used them 6 months ago and I remember that i was increasing them from the database

**Comment by GameRaiderCC** [comment]
ID of the Integrated Coupon is 6000001, adding the item and increasing the count of this item will increase the Coupon counter

**Comment by redapro** [comment]
Thank you .. but is there is a way to add specific item to  a single player ?

**Comment by GameRaiderCC** [comment]
yes: player_items (item needs to be defined in shop_iteminfos)

**Comment by redapro** [comment]
@GameRaiderCC  Yes , Thanks For All of that .I 've done this already but i mean how can i add an item to a specific inventory and also remove it...I tried removing a player item form player_items but items are still in inventory

**Comment by GameRaiderCC** [comment]
you have to go to serverlist and reconnect

**Comment by redapro** [comment]
Made This....Same
btw Thanks For Replying <3
