### ISSUE TITLE
[Error] No shop entry found

### ISSUE THREAD

**Issue by gabrielpop12** [wtfblub/NetspherePirates#233]
@wtfblub 
Hello, this problem for the following reason, I do not know if sea BUG or something I am doing wrong I change, I have everything well configured, I did not see that added added something changed in the configuration, so I guess it is a BUG.
I enter the store, and until I get to create 2 accounts and pass the next problem.

(Game.log)
`[Error] No shop entry found for "{ ItemNumber = 2000008, PriceType = PEN, Period = 0, PeriodType = None }"`

**Comment by BioAleks** [comment]
You no have this item in database.

**Comment by gabrielpop12** [comment]
@BioAleks there is the problem, the Items if I have them in the Database, is more, before the last modifications that was made to the files If I made the purchase, now with the latest modifications does not.

**Comment by GameRaiderCC** [comment]
dont forget ro change the shop version and to restart the server after a change

**Comment by BioAleks** [comment]
You can change shop version no only database.
Use server console command `reload shop`

**Comment by gabrielpop12** [comment]
I'm going to change the version, and tell you how I've gone

**Comment by gabrielpop12** [comment]
@BioAleks @GameRaiderCC change the version of the store, execute the command "reload shop" and continue with the same problem. Try other things but they have not worked.

**Comment by gabrielpop12** [comment]
With the last update, "DatabaseMigrator" has been fixed.
