### ISSUE TITLE
Web Files for Files

### ISSUE THREAD

**Issue by gabrielpop12** [wtfblub/NetspherePirates#236]
In advance sorry if annoying.
As I am always aware of this project, I have been thinking about creating a website for files for some time (I know it may be early to create this). It is very simple, I will add things and if at any time the structure of the database changes, I will update the files.

[https://goo.gl/YuQ9mF](url)

**Comment by de4th000gun** [comment]
Hi. I create website :) 
http://www.kepfeltoltes.eu/images/hdd1/2018/01/10/7091.jpg
http://www.kepfeltoltes.eu/images/hdd1/2018/01/10/8982.jpg
http://www.kepfeltoltes.eu/images/hdd1/2018/01/10/7163.jpg
current version
FIX:
Register
Login
Nickname change
