### ISSUE TITLE
Last build compile error

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#240]
Auth server compile error.
Line 129:
`session.SendAsync(new SAuthInEuAckMessage(AuthLoginResult.OK, (ulong)account.Id, sessionId));`

Error CS1503 Argument 3: cannot convert from 'uint' to 'string'	Auth	C:\Users\s4serv\Desktop\NetspherePirates-master\src\Auth\Network\Service\AuthService.cs	129	Active

Server no compile with last Visual. CMD compile - same error. 

Other projects compile perfect.

**Comment by wtfblub** [comment]
Fixed with ee01a2075ce153a1da769c8a60cda2a1d573b80e
