### ISSUE TITLE
How to use database migrator to update the databases

### ISSUE THREAD

**Issue by RedaGad** [wtfblub/NetspherePirates#245]
When i run auth. dll and game. dll  they require to update the databases version for the sql.
When i run database migrator it  requires me to exit

**Comment by RedaGad** [comment]
@wtfblub

**Comment by wtfblub** [comment]
I'll make a small tutorial on how to use it when I get the time(Probably next weekend)

**Comment by RedaGad** [comment]
Okay Thank You very much :) ...In this time i can read the code and understand it <3

**Comment by wtfblub** [comment]
https://github.com/wtfblub/NetspherePirates/wiki/Using-the-DatabaseMigrator
