### ISSUE TITLE
Source code (zip)

### ISSUE THREAD

**Issue by de4th000gun** [wtfblub/NetspherePirates#249]
I download old source and error. i search "work threads" option and i not look. not found..
Logfile:

`2018-01-05 12:15:12.2940|INFO|Program->Main:33||Checking database... 
2018-01-05 12:15:13.3821|INFO|Program->Main:49||Starting server... 
2018-01-05 12:15:13.8431|DEBUG|ResourceCache->GetChannels:72||Caching... 
2018-01-05 12:15:13.9241|INFO|ResourceCache->PreCache:26||Caching: Channels 
2018-01-05 12:15:13.9241|INFO|ResourceCache->PreCache:31||Caching: Effects 
2018-01-05 12:15:13.9241|DEBUG|ResourceCache->GetEffects:87||Caching... 
2018-01-05 12:15:13.9541|ERROR|Program->OnUnhandledException:114||UnhandledException 
System.ArgumentException: A kért „hp” érték nem található.
   a következő helyen: System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   a következő helyen: System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   a következő helyen: System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   a következő helyen: Netsphere.Resource.ResourceLoader.<LoadEffects>d__9.MoveNext() hely: C:\Users\DeathGun\Downloads\NetspherePirates-Pre-Build\NetspherePirates-Pre-Build\src\Game\Resource\ResourceLoader.cs, sor: 165
   a következő helyen: System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   a következő helyen: System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   a következő helyen: Netsphere.Resource.ResourceCache.GetEffects() hely: C:\Users\DeathGun\Downloads\NetspherePirates-Pre-Build\NetspherePirates-Pre-Build\src\Game\Resource\ResourceCache.cs, sor: 91
   a következő helyen: Netsphere.Resource.ResourceCache.PreCache() hely: C:\Users\DeathGun\Downloads\NetspherePirates-Pre-Build\NetspherePirates-Pre-Build\src\Game\Resource\ResourceCache.cs, sor: 34
   a következő helyen: Netsphere.Network.GameServer.Start(IPEndPoint localEP) hely: C:\Users\DeathGun\Downloads\NetspherePirates-Pre-Build\NetspherePirates-Pre-Build\src\Game\Network\GameServer.cs, sor: 225
   a következő helyen: Netsphere.Program.Main() hely: C:\Users\DeathGun\Downloads\NetspherePirates-Pre-Build\NetspherePirates-Pre-Build\src\Game\Program.cs, sor: 53
`

Please help.

**Comment by Demon0no** [comment]
Do NOT use the builds from the releases page!
Download them from the [appveyor](https://ci.appveyor.com/project/wtfblub/netspherepirates/branch/master/artifacts) instead!

**Comment by de4th000gun** [comment]
ahh thank you :)
