### ISSUE TITLE
Client side bug: Not dying when falling under some maps

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#25]
It's old bug.
If we use print screen (if we no have PC with very big performance ability) when we fall from map - we no die.
We may go under map. 
![oldschool_undermap](https://cloud.githubusercontent.com/assets/19153597/16960327/b4463882-4df1-11e6-93f5-ace2a4ea1ea3.png)
Screen from map "Old School"

**Comment by Vyre** [comment]
I don't think that this is relevant here since its client related and not about the emulator.

**Comment by BioAleks** [comment]
Something like that is not hard to fix and can be fixed by server.

**Comment by Vyre** [comment]
I'm pretty sure the positions of the lasers/death area's are client sided and are not set by the server. So no, I don't think you can fix it that easily without modifying the client. But I could be wrong :^)

**Comment by wtfblub** [comment]
Can be easily fixed server side but before i start fixing bugs like that i want to make sure the emulator reaches a stable state.

**Comment by BioAleks** [comment]
Blub, why "on Old School". It's no only old school :).

**Comment by BioAleks** [comment]
Are you reading...?
