### ISSUE TITLE
Shop color bug

### ISSUE THREAD

**Issue by de4th000gun** [wtfblub/NetspherePirates#250]
No color choices PEN , AP and Premium shop all found.

**Comment by de4th000gun** [comment]
I use netCore emulator this new.

**Comment by Demon0no** [comment]
This is not an issue with the server. The client just doesn't show the colors, because the pen shop isn't suppoed to have color variants in the first place. If you want color use the ap shop.

**Comment by BioAleks** [comment]
Yes.

**Comment by BioAleks** [comment]
Colors work in AP and Premium shop. 
Why color menu be with "0"? Change this.

**Comment by de4th000gun** [comment]
okay now good. thank you
