### ISSUE TITLE
Relay chat problem

### ISSUE THREAD

**Issue by handsomebananax** [wtfblub/NetspherePirates#259]
hi, i have little problems. if i use udp players cant see chats.Whats can i do ?

**Comment by wtfblub** [comment]
This is a known bug see #107. Turning udp off is currently the only workaround.

**Comment by handsomebananax** [comment]
if i use tcp will be lag :/

**Comment by BioAleks** [comment]
No lag with tcp. All ok for me

**Comment by handsomebananax** [comment]
@BioAleks hi again :D which ports do you using ?
