### ISSUE TITLE
LUA files are not decrypt

### ISSUE THREAD

**Issue by FreeDenny9700** [wtfblub/NetspherePirates#26]
Some problem of X7 files but LUA files are not decrypt when i try to extract this file.
Thanks for help

**Comment by wtfblub** [comment]
Decryption on lua files works fine they're just compiled.

**Comment by FreeDenny9700** [comment]
i have extracted this file with your DataExtractor tool but LUA is not Decrypted

![lua](https://cloud.githubusercontent.com/assets/19553583/16979595/31025eb2-4e62-11e6-9ec7-3605eb38652c.png)

**Comment by wtfblub** [comment]
How about reading what i said? Lua files are **compiled**

**Comment by FreeDenny9700** [comment]
Ah ok, sorry

**Comment by FreeDenny9700** [comment]
which version of lua lua is used to compile lua files for the S4 client?
New i have all LUA Decompiled
