### ISSUE TITLE
Error when trying to migrate the databases

### ISSUE THREAD

**Issue by redaamr** [wtfblub/NetspherePirates#266]
i'm trying to migrate the databases through cmd but there is an error ..You can see the error in screenshots
![untitled](https://user-images.githubusercontent.com/38199287/38478364-cd87032e-3bea-11e8-8e5b-512e9fd2d1f3.png)

**Comment by redaamr** [comment]
I have seen this wiki (https://github.com/wtfblub/NetspherePirates/wiki/Using-the-DatabaseMigrator) and also cannot do it ..Can someone help me ?

**Comment by Demon0no** [comment]
Add a space between your password and the --database flag.

**Comment by redaamr** [comment]
Yes I've seen it after posting the issue immdeiatly :D Thank you ...Fixed 
Closed

**Comment by redaamr** [comment]
Another Question  .What is the use of this migrator and how can i get a benefit from it

**Comment by redaamr** [comment]
@Demon0no

**Comment by Demon0no** [comment]
Since this emulator is in experimental phase, we expect the database to change at some point (for example when implementing new features that are not yet present in the database). The migrator can then update your old database to the new structure without you having to touch the database yourself.
