### ISSUE TITLE
Compile LUA files

### ISSUE THREAD

**Issue by FreeDenny9700** [wtfblub/NetspherePirates#27]
How i can compile LUA file after that i modify it?
Thanks for help

**Comment by wtfblub** [comment]
You download lua and run `luac.exe -o output_compiled.lua input.lua`

**Comment by FreeDenny9700** [comment]
I download a lot of version of luac for compile lua script. The best is LUAC 5.0 but when i compile LUA, (example Tutorial.lua), tutorial doesn't work. I think that we want a specific version of LUAC file.
I don't know this version unfortunatelly.
Thanks for your help

**Comment by Vyre** [comment]
I think the version you need was 5.1 or 5.2. Not quite sure which tho. After my last tests with lua, it was pretty hard to find on the internet so I can't give you a link or anything since I don't have it anymore, sorry.

**Comment by FreeDenny9700** [comment]
Thanks for your help, i test today a lot of version of LUAC

**Comment by FreeDenny9700** [comment]
I have tested all version of LUA file but nothing work. I don't know...

**Comment by wtfblub** [comment]
Its version 5.0 but pretty sure lua encryption is also broken not only x7 #22

**Comment by FreeDenny9700** [comment]
Ah ok, i wait your good work :)
