### ISSUE TITLE
how to create auto update launcher and more help ?

### ISSUE THREAD

**Issue by JaZzUpx2** [wtfblub/NetspherePirates#278]
how to create auto update launcher

and help in the s4 client how add weapon and costume

and web site register and login [{*-._.-*}} web site done

Some help?

**Comment by Demon0no** [comment]
>how to create auto update launcher  
  
Updating the client has nothing to do with the emulator itself. Also there's tons of ways to create auto updaters each with it's own advantages and disadvantages, just google around a bit and you'll find something to your taste.

>and help in the s4 client how add weapon and costume  
  
You're asking here how to add stuff to the client, which again has nothing to do with the emulator, but in case you're actually wanting to add them to the server:  
Add the items to the shop-tables in the game database, modify the shop_version and reload the server.

>and web site register and login [{*-._.-*}} web site done  
  
I answered this question on the issue you created in my NetspherePiratesWeb repository.
