### ISSUE TITLE
I´m need Help

### ISSUE THREAD

**Issue by s4archivos** [wtfblub/NetspherePirates#29]
Hello !!

I have a question

I would like to know how under the captian mode and also if you have a resource tool for season 1 that could pass me as I have a server created with your archivos..muchas thanks for the files ... eh created is that resien the season 1: D
I understand something xd

Please help

**Comment by shanzenos** [comment]
You'd have to add it in, as captain mode isn't finished in the server files. Also, while blub is apparently working on a season 1 resource tool, 2 others already exist you can find with ease. The thing is, until blub updates his libraries you can't import any .x7 file with any resource tool, which means that you can't really make any real changes to the client.

**Comment by DimitriuAdri** [comment]
that english please

**Comment by s4archivos** [comment]
Thank you very much for the help!!

**Comment by s4archivos** [comment]
ME COULD SPEND THE MOST UPDATED FILES de wtfblub

**Comment by shanzenos** [comment]
Any estimate on when you'll be fixing the libraries? Or if you are gonna do it when you finish your resource tool, is there any progress on that? Asking since there's really no other way to keep up with progress.

**Comment by DimitriuAdri** [comment]
Is not easy fix this kind of things, u must be patient and wait for the update...

**Comment by s4archivos** [comment]
I´m waiting

**Comment by wtfblub** [comment]
Then continue waiting. Like i already said on another issue: I'll work on this project when i feel like it and don't expect any updates.

**Comment by s4archivos** [comment]
ok thanks you!!
