### ISSUE TITLE
Level 100 in lobby. But level begınner ın game / room. Help me

### ISSUE THREAD

**Issue by Shurinka1** [wtfblub/NetspherePirates#290]
I logıned game. My level S4 (ı changed) ın lobby. But level begınner ın room and game. help me_

**Comment by Demon0no** [comment]
You have to set the level AND the corresponding experience in the database. If that didn't fix it relog.

**Comment by Shurinka1** [comment]
_I changed the level in the database. The level in the lobby is true. But we looks begınner_ in the room or in the game

**Comment by Demon0no** [comment]
And I said change the EXPERIENCE value too.  
Is reading really THAT hard?!

**Comment by Shurinka1** [comment]
IM Turkısh man. _How many experiences will I make

**Comment by Demon0no** [comment]
> IM Turkısh man.  
  
And I'm german, yet I can read english fine. Don't use your country as an excuse, that's just being lazy.

> _How many experiences will I make  
  
You can look up how much exp you need for each level in the levels.xml (or experience.xml or something like that) in the data/xml folder of the game server.

**Comment by WAZAAAAA0** [comment]
pour one out for our brave comrade @Demon0no, stuck spoonfeeding people in github support hell 🍷
