### ISSUE TITLE
A Small Tutorial For Creating Server 

### ISSUE THREAD

**Issue by Neroli-realy** [wtfblub/NetspherePirates#291]
mm i made a Small Video To Compile The Binaries ....... I hope you can add t to the Wiki 

Link:
https://youtu.be/P9Z8NVIKbm0
^_^

**Comment by Demon0no** [comment]
Can't watch this rn, as I'm on throttled mobile traffic, but is this just for compiling? Or do you also talk about configuration, setting up the database and these things? I don't think a tutorial just for compiling would make sense, because everyone who DOESN'T understand how to compile this would rather use the app-veyor builds.

**Comment by Neroli-realy** [comment]
mm i just wanted to see the people interaction if they liked it i can keep publish things like editing on the database and fixing some issues 

dude there are some people don't know how to start the .netcore applications 

so i well see what will happen 

+ 
the video contains how to start the server and set it up

using database migrator
using dataextractor
compilie with .netcore

just this ^_^

**Comment by Demon0no** [comment]
I'll watch it when I get time to do that.
You can open pull requests for the wiki yourself btw, that way wtfblub probably notices it earlier and decides if he wants to add ot.

**Comment by wtfblub** [comment]
I'm not going to add video tutorials to the wiki.

**Comment by Demon0no** [comment]
I now have watched a bit of the tutorial (just skipped through a few of the parts and stuff).  
  
Pros:  
 - The video quality seems pretty sharp (at least on my smartphone), I could read the text fine and everything
 - You keep it slow, so people can follow you easily  
  
Cons  
 - The notepad text with music tutorials are very outdated, especially at a length of 30 minutes this gets VERY dry to look at  
  
  
You should think about writing a script what to say (or just a list with the topics, if you're good at holding presentations) and just talk into the microphone, that way these kinds of videos get way more enjoying. You could even make a "lets play style webcam" like for example the youtube channel "the coding train".

**Comment by Neroli-realy** [comment]
@Demon0no  thx For Notes And I am busy too hhh it's my  first year at the collage 

so it was fast made 

@wtfblub 

i understand it's your project at the end :)

Thx again

**Comment by Neroli-realy** [comment]
@Demon0no  I wanted to Use Microphone But I was afraid that some  one cannot understand some words

any way it was a try and i will focus on fixing issues hhh

**Comment by Demon0no** [comment]
Don't be worried about accents and stuff, just remember to speak a bit slower than you would be in a casual situation. You won't be perfect the first time, but hey, by speaking english you'll actually improve over time. (I'm guessing here that english is not your native language, if it is, just ignore this.)  
  
You could also add cc subtitles to youtube if you're really worried. That way people can decide for themselves if they want to read or listen.

**Comment by Neroli-realy** [comment]
@Demon0no  maybe One day hh and thx for advice ... again

**Comment by Neroli-realy** [comment]
@Demon0no  yup english is not my native language
