### ISSUE TITLE
Cant't purchase any item in shop

### ISSUE THREAD

**Issue by sonick369** [wtfblub/NetspherePirates#33]
When i purchase an item i was getting this error
Screenshot: http://prnt.sc/c26ftk
Thanks for everything :)

**Comment by DimitriuAdri** [comment]
how did u to add items in the premium place?

**Comment by sonick369** [comment]
DimitriuAdri I don't add items in premium place because they are already being in premium place

Maybe this link can solve this problem
http://www.elitepvpers.com/forum/s4-league/4096587-playable-dark-lightning-emulator-6.html#post34960005

**Comment by BioAleks** [comment]
It's easy to add items to premium place or ap shop.

Error in your database. No CP for this item (no have this item type price in base).

**Comment by sonick369** [comment]
When I added items in ap shop i was trying to purchase I am getting another error.
As I said:
"Maybe this link can solve this problem
http://www.elitepvpers.com/forum/s4-league/4096587-playable-dark-lightning-emulator-6.html#post34960005 "

I haven’t had time to try it yet. :(
