### ISSUE TITLE
Start items - error

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#35]
I add in database start items.
It's every time say like "invalid item price type. Forgot to reload shop?" (when all work normal and i have this price type and yes, i reload shop).

Blub???
> 2016-08-06 19:42:50.8001|WARN|AuthService->LoginAsync:396||Cant find ShopPrice for Start item 3000000 - Forgot to reload the cache? 
or
2016-08-06 19:42:50.8001|WARN|AuthService->LoginAsync:396||Cant find ShopPrice for Start item 1 - Forgot to reload the cache?

**Comment by wtfblub** [comment]
Like the error already says: Your start items reference a ShopPrice id that doesn't exist in the database.

**Comment by BioAleks** [comment]
I check database Blub, you no read my message?
I have that shopprice id.

**Comment by wtfblub** [comment]
Should be working now

**Comment by BioAleks** [comment]
Thanks.

**Comment by BioAleks** [comment]
I test it. No work. Same error.

**Comment by wtfblub** [comment]
Did you use the new version? You have to compile it yourself or download it from the build server  [here](https://ci.appveyor.com/project/wtfblub/netspherepirates/build/artifacts)

**Comment by BioAleks** [comment]
Yes.

**Comment by BioAleks** [comment]
Yes. I can change code (what you change) or use github and compile in my pc. Vusial studio.

**Comment by BioAleks** [comment]
I change files, use reload and etc, but don't understand why server spam this error.

**Comment by BioAleks** [comment]
I see today that item with id like "1000" work like start items, but id "0, 1, 2" etc - no.

**Comment by BioAleks** [comment]
Working for now.
