### ISSUE TITLE
3 Problem

### ISSUE THREAD

**Issue by sonick369** [wtfblub/NetspherePirates#36]
Capsule Problem(GIF)
http://prnt.sc/c2ile2

Item Drop Problem(GIF)
http://prnt.sc/c2iqxu

Resell Problem(GIF)
http://prnt.sc/c2irma

(Sorry for my speed because this program limited 10 seconds for record gif)
-edit
Added Item Drop Problem's log
[debug_2016-08-06.txt](https://github.com/wtfblub/NetspherePirates/files/405238/debug_2016-08-06.txt)

**Comment by DimitriuAdri** [comment]
Capsules code are not implemented yet I think.

**Comment by sonick369** [comment]
I know capsules didnt'd added but this server's answer so unexpected :D
Maybe Item drop has been added yet.

**Comment by BioAleks** [comment]
Yes, no code.

>Capsules code are not implemented yet I think. ItemDrop i don't know and resell too xD

**Comment by wtfblub** [comment]
Dont put multiple reports into one issue. Open a new issue for every type of problem. In your case: 1 for capsules and 1 for item drop/resell.
Also dont use gifs...

**Comment by DimitriuAdri** [comment]
For people who want this, you can modify your name pasting this: {F-2002_15}{CB-0,255,255,255} and your name. For change colour, modify the numbers. Remember that this will not be hidden in your name, you'll only see your name different when u write something in the chat.
