### ISSUE TITLE
Missing config for udp relaying(listener, enable/disable)

### ISSUE THREAD

**Issue by wtfblub** [wtfblub/NetspherePirates#4]

**Comment by BioAleks** [comment]
How about add "log level" too?
Like log level 1 only "red" (critical) errors, log lvl 2 - with "yellow messages", etc.

**Comment by wtfblub** [comment]
Logging configuration is inside the [App.config](https://github.com/wtfblub/NetspherePirates/blob/master/src/Game/App.config) file.
