### ISSUE TITLE
Cant't purchase any item in premium shop

### ISSUE THREAD

**Issue by sonick369** [wtfblub/NetspherePirates#40]
New release giving error to me but old release isn't giving error to me.( I am using same database )

2016-08-10 12:51:03.3569|ERROR|ShopService->BuyItemHandler:290| [test<4>-User]|Unknown PriceType CP

**Comment by BioAleks** [comment]
PriceType 1 - pen, 2 - AP, 3 - Premium (if you use Huenato patch or huenato server).
Close.

**Comment by sonick369** [comment]
What is the huenato patch and where can I find ?

**Comment by BioAleks** [comment]
https://github.com/wtfblub/NetspherePirates/pull/20
