### ISSUE TITLE
Sqlite not working on mono

### ISSUE THREAD

**Issue by huenato** [wtfblub/NetspherePirates#43]
<img src="https://puu.sh/qBdOJ/9b00e2cf6c.png" />

**Comment by wtfblub** [comment]
Which version of mono are you using? `mono -V`

**Comment by huenato** [comment]
At first, my mono version was outdated (4.2), so I installed the 4.4.2 one.
Auth was running fine but Game on mono v4.2.

After updating to 4.4.2, both are not working anymore.

<img src="https://puu.sh/qC5eF/3395b83dbe.png" />
<img src="https://puu.sh/qC5fV/560e30c081.png" />
<img src="https://puu.sh/qC5lJ/f361210436.png" />

**Comment by wtfblub** [comment]
re-opened this issue for details see 7fab1809d7f4e48b77a4be7b49393fdf69c008ad

**Comment by wtfblub** [comment]
Dropped sqlite support with .net core 2
