### ISSUE TITLE
[Request] Start a match with only 1 player in a room

### ISSUE THREAD

**Issue by Tpk86** [wtfblub/NetspherePirates#48]
As the title says, i would like to ask if it's possible start a match with only 1 player in a room.
I think this is a useful feature because S4 is based on jumps and learn / training for the tricks is an important part of the game.
At the moment there are not so many active servers and the opportunity to do this thing without need to install virtual machine, etc... can be really nice.

So my request is that:
Can you give us the possibility to start a match with just 1 player in a room and no kick ?
Thx you

**Comment by BioAleks** [comment]
You can start BR with 1 player. Just need to change 2 line codes.

**Comment by Tpk86** [comment]
Hi BioAleks, thx for the tip but i' m not a programmer and to be honest i have no idea how to do that.

**Comment by FreeDenny9700** [comment]
With pre-build version you can't compile source with mod.

**Comment by Tpk86** [comment]
Eng:
Hi FreeDenny9700, i take a look on the web but i don't found a detailed guide about "how to compile a server" for S4 League.
I found some guidelines for other servers of other games then also use github, but i' m not sure that is the same thing.
At this point i think it's better if i just wait the decision of WtfBlub about made or not made this feature or wait if in future someone make a detailed guide on this so i can try to do that.
Thx for the help anyway

Ita:
Ciao FreeDenny9700, ho provato a cercare un pò su internet ma non ho trovato una guida vera e propria che spieghi "come compilare un server" per S4 League.
Ho trovato delle cose simili ma da quello che ho capito partono tutte da dei repository di github, però qui ci sono solo i file.
Penso sia meglio che io aspetti la decisione di WtfBlub o una guida dettagliata.
Grazie dell' aiuto cmq

**Comment by FreeDenny9700** [comment]
Tpk86 if you are italian you can add me on Skype. I can help you for compile your source.
PS: i'm italian but on GitHub i prefer speak english such as other people :)

**Comment by wtfblub** [comment]
> just wait the decision of WtfBlub
Don't wait for anything. I'm not actively working on this project. When i feel like working on this i'll pick some random things from the todo list and start/finish it.

**Comment by Tpk86** [comment]
@FreeDenny9700
Si, sono italiano. Ti lascio il mio skype visto che non c'è il tuo :P
Skype: Tpk_86 di Torino

@WtfBlub
Sure, no problem at all.
However, i take this opportunity to thanks you for your work and for give us this opportunity :)

**Comment by FreeDenny9700** [comment]
I have been send you friend request :)
