### ISSUE TITLE
Server check game version

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#49]
Blub, add this in "Feature-NYI" label.
I think it's important thing.
Now I have launcher (game updater) for client, but server no check game version (and of course no drop users if version - another). It's problem.

So, need add server check game version function like: server have last version info and send version request for client. Client send answer and if version another - drop client with message (red letters) "update your client".

**Comment by wtfblub** [comment]
The server already checks the version: https://github.com/wtfblub/NetspherePirates/blob/master/src/Game/Network/Services/AuthService.cs#L34

**Comment by BioAleks** [comment]
And from? From client? How?
If in server no file version - people can use resource tool or etc for cheat game version.

**Comment by wtfblub** [comment]
The client sends its own file version.

**Comment by BioAleks** [comment]
What file?

**Comment by BioAleks** [comment]
Which file? S4Client.exe?

**Comment by wtfblub** [comment]
Yes.

**Comment by BioAleks** [comment]
Thx.

**Comment by BioAleks** [comment]
Thx.
