### ISSUE TITLE
SQLite to MySQL - guide request

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#50]
Add guide for change and port base SQLite to MySQL.
Or add base MySQL files with guide.

**Comment by wtfblub** [comment]
The emulator creates the database for you if it doesn't exist. Thats why i didn't include any sql files for the base structure.
All you have to do is change engine to MySQL and insert host, username, password and database name in the config files.

**Comment by Tpk86** [comment]
I think i managed how to do it.
You need to do exactly what WtfBlub said.
I posted my "Auth.json" and "Game.json" if someone need.
Remember to change the password with yours, MySQL default id and password are: "root"

Auth.json:
http://pastebin.com/xsTn7x8T

Game.json:
http://pastebin.com/cqgKgN67

**Comment by DimitriuAdri** [comment]
Thanks for help. I have a little problem, i just config all line codes and friends can enter with the external ip but i only can enter to serverlist and no game server. Thanks for help :100:  :+1:

**Comment by Tpk86** [comment]
You have a dynamic or static ip ?
If you use the same .json then me, you just need to use your localhost in your .bat.

Example:

Start.bat for you
start S4Client.exe -rc:eu -lac:eng -auth_server_ip:127.0.0.1

Start.bat for your friends
start S4Client.exe -rc:eu -lac:eng -auth_server_ip:YOUREXTERNALIPHERE

**Comment by FreeDenny9700** [comment]
Remember that you must insert port rules on firewall option (if you using Windows)

**Comment by BioAleks** [comment]
Newtonsoft.Json.JsonReaderException: Input string '192.168.1.10' is not a valid number.
Why?
I can't use this local ip (I have router) for server?
