### ISSUE TITLE
Question - Ip Config

### ISSUE THREAD

**Issue by z900** [wtfblub/NetspherePirates#51]
Hello everyone.
Me and a friend are trying to play together.
Server works fine, auth and game runs fine and i can connect but my friend can't log in.
He gets always a message like "wrong id or pass" or "failed connection to the relay server".
We have tried different solutions, from external ip, to ddns, to Hamachi but looks like nothing works.
We are using the prebuild version.
What we need to change for play together ? I tried also to find a config file or an xml with the settings for the ip but i don't see anywhere.
Thx for the help

**Comment by BioAleks** [comment]
1. You change ip in config files to your internet ip (no local ip)?
2. Your friend start game with this ip?
3. If you have router - open ports.

**Comment by wtfblub** [comment]
`auth.json`:
- Replace `127.0.0.1` with `0.0.0.0` in the **FIRST** line with `"listener":` - No need to touch the second one

`game.json`:
- Replace `127.0.0.1` with `0.0.0.0` in `"listener":`, `"listener_chat":` and `"listener_relay":`
- Replace `127.0.0.1` with the ip your friend needs to use to connect to you in `"server_ip":`

And make sure the following ports are open in your firewall and router configuration: 
- **TCP:** 28002, 28003, 28004, 28005
- **UDP:** 22000

**Comment by z900** [comment]
Thanks guys, problem solved !

**Comment by DimitriuAdri** [comment]
I'm using the ipv4 ip from my internet and my friends can't enter with the public ip. Ports are open, firewall are down and .json files have the correct code. Did you know how to fix this?
