### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#53]
What is the Auth database >>Accounts >> Password Encryption?
## How to change to mysql in order to open the newest server source (Auth + Game , As i mentioned the error before)

Thanks

**Comment by wtfblub** [comment]
You can see [here](https://github.com/wtfblub/NetspherePirates/blob/master/src/Auth/Network/Service/AuthService.cs#L43) how the password gets generated.

First you have to generate a random and unique salt and then you make a string: "password+salt" and hash it with SHA1 and thats your password.

**Example:**
Username: test
Password: 123
Salt: 1cacd7bfb3d11840525af21dec79441b0200d718
Password in database = sha1("123+1cacd7bfb3d11840525af21dec79441b0200d718") = 8f6d76dfd2195912014afc153c36a20882538ba5

And for setting up the MySQL config see #50

**Comment by redapro** [comment]
ALSO, Another question ..Can I Edit in the source to make season 2 data work in it ???
