### ISSUE TITLE
Question - Start event

### ISSUE THREAD

**Issue by Tpk86** [wtfblub/NetspherePirates#55]
Hi guys.
I' m trying to figure out how to start a match with only 1 player.
I think there is something linked to the GameRuleStateTrigger or cbeginroundreq.
In Chaser or Br there is a function "playerneedtostart" but i can't found / understand what rule that thing in the other gamemodes.
Any help / suggestions are appreciated.

**Comment by DimitriuAdri** [comment]
If you change the players requiered in TD or DM, game will go automatically to results cause there are no many players to continue the match. You need to modify more things.

**Comment by Tpk86** [comment]
Thx for the fast reply DimitriuAdri.
Arg... I did not think about it, it's more complicated than I thought Q_Q
Maybe if i change the condition about the end of the match ?
Something like : the match is over only if the countdown reach the 0
Or there is a better way (and maybe more easy) ?

**Comment by DimitriuAdri** [comment]
Mmm you can try to modify GameRuleBase, GameRuleFactory or GameRuleManager. There are all the code of the gamemode. It's not difficult delete some references but the problem is... where are there? Maybe i don't know, sorry.

**Comment by Tpk86** [comment]
Sorry for the delay in replying.
For now i have not been very successful, still trying.
No problem, as i said "any help or suggestions are appreciated :)

**Comment by DimitriuAdri** [comment]
Good luck. If I get something, I will post there.

**Comment by Tpk86** [comment]
Dimitriu, what bypass are you using ? Can you tell me the name or give me the link ?

**Comment by DimitriuAdri** [comment]
Sandboxie is a free multiclient, you can open two games at the same time. Only install it and ejecute with sandboxie (right click). I will not post there any link sorry.

**Comment by FreeDenny9700** [comment]
I have One multiclient for Season 1 . No sandboxie

**Comment by Tpk86** [comment]
@DimitriuAdri
It worked ! Finally i can do some jumps on the maps *_*
Pretty happy about that. Thx !

@FreeDenny9700 
Ciao Denny, non riusciamo mai a beccarci. Fammi sapere quando sei disponibile che (se ti va) proviamo a continuare quella cosa ok ? Lasciami pure un messaggio su Skype o sulla mail di YouTube, tanto li controllo praticamente 3 volte al giorno

**Comment by FreeDenny9700** [comment]
Ti ho lasciato il mio numero su Skype, segnalo
