### ISSUE TITLE
Important Question

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#56]
1-How to add weapons to  the Client?Please Answer with steps
EX:I Have Mach3.dds + Mach3.scn ...I Wanna Add them instead Replacing (Cause Replacing in bad +The scn comes black color in any scn i  replace )

2-How to changes prices  of items?Please Answer with steps

3- How to send items from Pen Shop to Ap Shop?Please Answer with steps
Ex: SummerChest + Taser are in Pen Shop i wanna send them to Ap Shop with the Price of Ap ....

4-In player_items table >> the purchase date is in which format ??

5-Also in old source  ...There was 5 colors of the bat and 5 of Idol ,cs ,many items where having many colors to  choose from when i click on them (different types of the same item)..Now i cannot find this option in the new source..How to enable it again ?

Thanks , 
Reda

**Comment by wtfblub** [comment]
1. Theres no resource tool atm
2. shop_price_groups and shop_prices
3. shop_price_groups
4. Unix timestamp
5. shop_items -> Colors is the number of colors the item has

**Comment by FreeDenny9700** [comment]
If you want, you can use my ResTool on my GitHub based on Blub Libraries. With this tool you can't modify x7 or LUA file but if you want, you can replace One of models of Spy dagger with mac3. Have Fun

**Comment by redapro** [comment]
Free Denny , Is your restool has the ADD Function Working ?
----------------------------
wtfblub.How to enable the colors ? + Still 3- How to send items from Pen Shop to Ap Shop?Please Answer with steps
Ex: SummerChest + Taser are in Pen Shop i wanna send them to Ap Shop with the Price of Ap ....

**Comment by FreeDenny9700** [comment]
Add function work fine but you can't add weapon or some item to x7 files. Try to replace an existing model

**Comment by DimitriuAdri** [comment]
With his resourcetool, you can modify some files. I tried to modify some .dds and it works, only interface but that's nice :D

**Comment by redapro** [comment]
FreeDenny , Ur Res tool says to me..Sharplizo send an expection when i do any function!
Can you say to me how to fix it .?Do you have facebook?

**Comment by FreeDenny9700** [comment]
Extract all files and open .exe as Administrator. If you have any problem, you can open new issues on my GitHub page related to my project

**Comment by redapro** [comment]
+ Still 3- How to send items from Pen Shop to Ap Shop?Please Answer with steps
Ex: SummerChest + Taser are in Pen Shop i wanna send them to Ap Shop with the Price of Ap ....

**Comment by BioAleks** [comment]
https://github.com/wtfblub/NetspherePirates/issues/33

**Comment by redapro** [comment]
Still.nothing.changed!!!!

**Comment by redapro** [comment]
Still 3- How to send items from Pen Shop to Ap Shop?Please Answer with steps Ex: SummerChest + Taser are in Pen Shop i wanna send them to Ap Shop with the Price of Ap ...
