### ISSUE TITLE
Unknown PriceType CP

### ISSUE THREAD

**Issue by Tpk86** [wtfblub/NetspherePirates#57]
Hi guys.
When i try to buy a premium item, i get this error on the console :
[ShopService->BuyItemHandler:290] [TEST<3>-User] Unknown PriceType CP

I think it happens because the server expects to get the CP but this is not set on the database.
Someone know how to solve that or can upload an .sql with prices working ?

**Comment by BioAleks** [comment]
[https://github.com/wtfblub/NetspherePirates/issues/33](url)

**Comment by Tpk86** [comment]
Hi BioAleks.
I read all the whole discussion, they talk about change to the price in the db but i don't find any value of this.
Can you tell me the name of the table plz ?

**Comment by FreeDenny9700** [comment]
Se hai la possibilità mandami un messaggio normale al mio numero così mi collego

**Comment by Tpk86** [comment]
@FreeDenny9700 Scusa Denny ma non posso dare in giro il mio numero :(

@BioAleks Thx ! This topic solve a lot of my problems ^_^
