### ISSUE TITLE
Fast!!!!

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#58]
Still 3- How to send items from Pen Shop to Ap Shop?Please Answer with steps Ex: SummerChest + Taser are in Pen Shop i wanna send them to Ap Shop with the Price of Ap ....

**Comment by shanzenos** [comment]
You do all of that in the database its self. In patch26 all the things like patch9`s costume xml or shop xml`s are handled by the database.

**Comment by wtfblub** [comment]
Dont spam issues. You already opened a issue with this question.
