### ISSUE TITLE
Question!!

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#60]
In Database , 
Password field encryption comes From What (according to what) ? 
Salt Field Encryption comes From What (according to what)?
+How to decrypt and what's their use
----------------------------------------------------
What are the commands of an Admin  - GM-Developer..........Commands which kick or level up ..Do anything ingame!

**Comment by Dexelir** [comment]
It is SHA1.

Salt = sha1(account.password)
Password: sha1(account.password + "+" + Salt)
