### ISSUE TITLE
Password hash type?

### ISSUE THREAD

**Issue by ZenCorporation** [wtfblub/NetspherePirates#61]
Hi I want to know how the password are hashed. And how to get the salt. Thx in advance!

**Comment by Dexelir** [comment]
It is SHA1.

Salt = sha1(account.password)
Password: sha1(account.password + "+" + Salt)

A PHP code for you ( probably you wanted this for a reg page :+1:  )
`
$Salt = sha1($_POST['password']);
$Password = sha1($_POST['password'] . "+" . $Salt);
`
