### ISSUE TITLE
Another Server Error

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#62]
Since this source has an error on load so i am suing an earlier source....It has a bug when i create an account i can wear everything but i have to rejoin the server to wear weapons and skills if this have a fix please give me it's link of fix...
Also  sending  a friend req. gives Dc send me a fix also

**Comment by BioAleks** [comment]
Really, USE FU***** search!
https://github.com/wtfblub/NetspherePirates/issues/18
