### ISSUE TITLE
MySQL problem

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#65]
Newtonsoft.Json.JsonReaderException: Input string '192.168.1.10' is not a valid number.
Why?
I can't use this local ip (I have router) for server?

It's when I change database to MySQL.
So, what IP I can use? (hostname)
Words hostname like "blablabla"? Server say error too. 
I bind my pc ip to this one (local ip i mean).

Error same with "127.0.0.1" too. I test all ip, hosts.
MySQL connection - stable, working.
Same with game server.

Add full error message (with ip use):
[mysqldb.txt](https://github.com/wtfblub/NetspherePirates/files/519337/mysqldb.txt)
Error when use word hostname (like localhost):
[mysqlerr2.txt](https://github.com/wtfblub/NetspherePirates/files/519360/mysqlerr2.txt)

**Comment by wtfblub** [comment]
You forgot to put it inside ""

**Comment by BioAleks** [comment]
I no see in config files "" and it's why i no put all code in "".
I try only with ip this. Now if with all - works. Sorry and thanks :).

**Comment by BioAleks** [comment]
I no see in config files "" and it's why i no put all code in "".
I try only with ip this. Now if with all - works. Sorry and thanks :).
