### ISSUE TITLE
No logs...

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#67]
Ehm...after your "logging cleanup" update server no have log files.
No create it. 

I need this because last update after big up time close server with error.
If like 30 minutes up time - no close error.

**Comment by wtfblub** [comment]
Works fine for me. Make sure you have the .config files. They contain the logging configurration.

**Comment by BioAleks** [comment]
Yes, i have it.

**Comment by DimitriuAdri** [comment]
It works for me too. Download the server again.
