### ISSUE TITLE
Turrets server problem

### ISSUE THREAD

**Issue by DimitriuAdri** [wtfblub/NetspherePirates#68]
In the old version that you just posted, turrets and sentys are bugged again. That's all XD

**Comment by wtfblub** [comment]
#11 was never fixed.

**Comment by BioAleks** [comment]
Yes?
https://github.com/wtfblub/NetspherePirates/pull/20
Huenato patch fix this and no only this. You no add here patch in server.

**Comment by DimitriuAdri** [comment]
Yeah but no problem, i only create this post to advice that
