### ISSUE TITLE
Changing the room options leads to a client crash

### ISSUE THREAD

**Issue by wtfblub** [wtfblub/NetspherePirates#7]

**Comment by BioAleks** [comment]
Don't know are you need this, but I add error message.
[roomruleschange.txt](https://github.com/wtfblub/NetspherePirates/files/367303/roomruleschange.txt)

**Comment by BioAleks** [comment]
https://github.com/wtfblub/NetspherePirates/commit/908bb949c677a02f55a96adb510715685eb461c5
It's working okay now.
