### ISSUE TITLE
Earth Bomb old bug + new one

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#70]
If player drop earth bomb and die - earth bomb instantly explode without waiting time for explode.

Bug 2: earth bomb no have player small knock-back effect and have stop action effect.

How need be:
Action stop (example: attack) only lightning bomb. Earth bomb only damage.

**Comment by DimitriuAdri** [comment]
Bug 3: Impossible add new earth bomb or lighting bomb with attack animation

**Comment by wtfblub** [comment]
They're all client side bugs.

**Comment by BioAleks** [comment]
No way to add time explode to server and check, and check die player or no?
It's a problem (old bug)...
