### ISSUE TITLE
Dev console does not work on any security level above 0 for an account

### ISSUE THREAD

**Issue by shanzenos** [wtfblub/NetspherePirates#73]
Dev console only works on 0 security level accounts, anyone any level above that can't even access the dev console.

**Comment by BioAleks** [comment]
How open dev console?

**Comment by shanzenos** [comment]
f11

**Comment by BioAleks** [comment]
I ask because F11 no open console for me. 
So, it's because security level problem. Okay. Thx.
Console work on any language startup?
