### ISSUE TITLE
Items variation colours

### ISSUE THREAD

**Issue by DimitriuAdri** [wtfblub/NetspherePirates#75]
Hi. I have a question, how colour works in season 1? in the beta was only add <texture_suffix.... but in season 1 it didn't works. someone knows how? thx

**Comment by BioAleks** [comment]
Add in database table "shop_items" color (if only one = 0, if 2 = 2).

**Comment by DimitriuAdri** [comment]
Yeah it's logic but it didn't works for me. I'm not speaking about the database. I'm speaking in the client iteminfo.x7 u.u "in the beta was only add <texture_suffix.... but in season 1 it didn't works."

**Comment by BioAleks** [comment]
I say you answer. Use database.
Not client suffix.

**Comment by DimitriuAdri** [comment]
Mmm ok i will try thanks you man 👍
