### ISSUE TITLE
Client crash when You add new weapon

### ISSUE THREAD

**Issue by FreeDenny9700** [wtfblub/NetspherePirates#76]
When You try to add new weapon such as Frypan Storm Bat and You join into room, during loading, client crash.

More weapon like Guillotine can be added into game without client crash but new weapon (Season 3 / Season 4 etc.) can't be added into game.

**Comment by shanzenos** [comment]
@FreeDenny9700  Haven't had this happen with any new models yet. You can only add models, not new weapons (like season 3 blades for example). Crashing client is usually an SCN issue, but scn's straight from official should work fine. All the new weapon skins and clothes I've added do.

**Comment by FreeDenny9700** [comment]
In game i can view my FryPan and it work perfectly. When i create room, boom.. crash. If i equip this item when i am into room and start game, i can play with this weapon but few seconds later room crash

**Comment by BioAleks** [comment]
Old scn files and new scn files have other versions.

**Comment by BioAleks** [comment]
Update.
+ See problem. Add kimono hair. When i start go in room after loading - client crash.
So, it's client side bug.

**Comment by wtfblub** [comment]
Sounds like you're missing animations. Make sure you also have all needed .seq files and maybe you also need to replace the male and female model files too.

**Comment by BioAleks** [comment]
What program use to open .seq files?

**Comment by BioAleks** [comment]
Sounds like you're missing animations, yes.
But no for my model. I have all seq, dds in effects, but this costume item from japan client no working.
I replace male/female models.

So, it's read bug or corrupted .scn (but i use official s4 files and i have all of it).

**Comment by DimitriuAdri** [comment]
Yes is an animation problem. I was trying add the breaker and other weapons but .lua files can be readed now so I can't modify the main file where the rest of .lua files are linked. I'm working on animations now and the priority for that problem are .lua files. Sorry english.

**Comment by DimitriuAdri** [comment]
Update: More weapons or costumes that i added, works when i enter to the game but when i move pressing S or D, it crashes XDDDDDD

**Comment by BioAleks** [comment]
How about change lobby to new lobby model?

**Comment by BioAleks** [comment]
So, why only in lobby?

**Comment by DimitriuAdri** [comment]
Added all scn, seq files and lua files too and i can see that some animations works perfectly, not all :/

**Comment by FreeDenny9700** [comment]
Edit: All resources are into game, client crash.
ClientSide Bug.

**Comment by BioAleks** [comment]
So, how to fix this shit?

**Comment by FreeDenny9700** [comment]
No way for now  :X

**Comment by BioAleks** [comment]
Have full scripted weapon. This just crash client. No way...
Spanish s4 (darkspirit) admin say that use old x1 resource tool for editing (patch 9).

**Comment by wtfblub** [comment]
Please extract a map model and import it again and try if the map still works when it works its not the resource tool.

**Comment by BioAleks** [comment]
Spanish client same version.

**Comment by BioAleks** [comment]
Update:
Map work (from same client or any other).
Korea map work too (same map have bigger size).
But problems no with map. Problem with some clothes and new weapons.

**Comment by BioAleks** [comment]
I no understand on this scripts only one thing.
What is the ability type? Where it can be fond and for what it used?

**Comment by FreeDenny9700** [comment]
Blub resource tool work fine, i can add some .scn file of Season 2 like Guillotine, Crash Storm Bat, etc.

**Comment by Devyre** [comment]
> What is the ability type in items weapons? Where it can be fond and for what it used?

I've been trying to find out the same thing. Didn't find anything though, so I am guessing it's hardcoded in the client.

**Comment by BioAleks** [comment]
We have problem with new seasons, no season 2.
New season have another .scn version files. And it's no only version. 
Structure too another.

**Comment by BioAleks** [comment]
Is weapon need be added in server too?
Like animation stats or another thing?...

**Comment by BioAleks** [comment]
![s4_20161018_170708](https://cloud.githubusercontent.com/assets/19153597/19481229/ea4c05a0-9555-11e6-8b64-3ea824acd547.jpg)
All that i have from full scripted model - this. Seriously?
Client no read model, ehhm...

**Comment by DimitriuAdri** [comment]
Client reads the scn perfectly. The problem is the animation linked to the Ability type. So there no are position for the breaker in the "hand". It's logic :3 :)

**Comment by BioAleks** [comment]
I'm say same thing lol.

**Comment by Devyre** [comment]
Since I am unable to find ability type in any lua file I am guessing its hard coded in the client. (Just like the NormalStates, RunStates, DamageStates?)

**Comment by Joraileds** [comment]
i's possible decompile .lua file? i can decompile the aeria .lua files but not season 1 files sorry english

**Comment by BioAleks** [comment]
`i's possible decompile .lua file? i can decompile the aeria .lua files but not season 1 files sorry english`
https://github.com/FreeDenny9700/S4_LUA_Decompiler

**Comment by Joraileds** [comment]
Oh bioaleks thanks, i had this one later but i didn't know that it works for season 1 client XD

**Comment by BioAleks** [comment]
`Oh bioaleks thanks, i had this one later but i didn't know that it works for season 1 client XD`
Lua files in season 1 compiled?
I no have tested this tool to this season, but it work for many clients (not 2016 korea. Lua files version - another).
I just link this think that you no have this :3, but test it.

**Comment by Joraileds** [comment]
Can't decompile files like actorstate_gameplay.lua. It don't works for season 1 but no problem thanks for help

**Comment by BioAleks** [comment]
`Can't decompile files like actorstate_gameplay.lua. It don't works for season 1 but no problem thanks for help`
Decompile another actorstate (example: client 2014).

Here client for pre-release season 1. 
Season 1 and pre-release season 1 - different thing.
Pre-release - old interface, season 1 - new.
For me all work (decompile).

**Comment by BioAleks** [comment]
![s4_20161020_003332](https://cloud.githubusercontent.com/assets/19153597/19538483/e7dfb08e-965c-11e6-983c-2f38c0fbf2fe.jpg)
Now I understand and have breaker animations.
But model no load. :)
Help plz? :3

**Comment by Devyre** [comment]
> Help plz? :3

> Ability type...hm...

Ability types are hard coded in the client.
You can't add new weapons without modifying the clients source code (which we don't have).

**Comment by Joraileds** [comment]
U have the link of the client 2014? I was working on this and i get the same like you but only in the preview of the shop. I didn't find any client to work on this.

**Comment by BioAleks** [comment]
> U have the link of the client 2014? I was working on this and i get the same like you but only in the preview of the shop. I didn't find any client to work on this.

No. I have client on my pc. Use search. 
Ability type = link to weapon. It's why no model load. -_-
`Ability types are hard coded in the client.`

**Comment by Joraileds** [comment]
"I didn't find any client to work on this." i said that's why i said it because i used that. No problem, i have Plays4l client and it works for me now.

**Comment by Devyre** [comment]
> U have the link of the client 2014?

You'll be unable to log in with such a late client because the emulator is made specifically for the 2011 client.
So If you want to be using such a client, you would have to modify the emulator.

Actually you can use almost any client, you would just need to reverse it in order to get rid of the hackshield.

And every client after mid 2014 uses the aeria_acc_code. Keep that in mind.

**Comment by Joraileds** [comment]
Lol I said that to take files not to use them XD!!!!!!!

**Comment by Devyre** [comment]
> Lol I said that to take files not to use them XD!!!!!!!

If you just want the resources, why not use the official ones? There isn't going to be much of a difference.

**Comment by Joraileds** [comment]
The files of the season 3 or 4 are not the same of actual files man. We are speaking about .lua files -.-. Read the rest of comments. You are trying helping me but u have no idea I think.

**Comment by Devyre** [comment]
> The files of the season 3 or 4 are not the same of actual files man. We are speaking about .lua files -.-. Read the rest of comments.

They actually are, especially the lua files
Maybe some additions but no real change in code, thats what I was referring to in the first place

So no idea what you're trying to find in season 3's files that you can't find in the official ones, no hate

**Comment by FreeDenny9700** [comment]
Actually i have all Season 3 Resources but i haven't time to test it.

**Comment by ofignacio** [comment]
> Actually i have all Season 3 Resources but i haven't time to test it.

How to repair this?

**Comment by FreeDenny9700** [comment]
Repair?!

**Comment by ofignacio** [comment]
> Repair?!
Season 3 items

**Comment by FreeDenny9700** [comment]
File must be adapted to Season 1 client

**Comment by HARUWEEN** [comment]
all these idiots saying "files need to be adapted to season1" "clientside glitch" you guys are fucking stupid. I added mach3 dagger. Not a single file needs to be "adapted" lol it's all YOUR-BRAIN-Sided. 
![s4_20161203_221418](https://cloud.githubusercontent.com/assets/24318940/20867744/c6a89d82-ba4b-11e6-8b36-4acdf02e85fb.jpg)

**Comment by FreeDenny9700** [comment]
Clap clap clap

**Comment by HARUWEEN** [comment]
LOOL you're actually retarded

**Comment by FreeDenny9700** [comment]
ohh you are a Genius...
pff

**Comment by Devyre** [comment]
> LOOL you're actually retarded. I have nothing to prove but i just tried adding frypan, it works fine? lol...
Feels bad when you're trying to be the smart ass but then find out that we're right, huh?

We never said that every item needs to be adapted, but some do.
Frying Pan Stormbat, Taichi Twin Blades and like 3 other force packs. Some clothes aswell.

Again, in game screenshots -- in case you wanna keep shit-talking.

**Comment by FreeDenny9700** [comment]
Oh My God, it work for me, i'm a genius 1!1!1!11!

[http://imgur.com/2JhfCn1](url)

**Comment by HARUWEEN** [comment]
shit-talking? buddy i have nothing to prove to some amateur kids who wanna make a server but don't know anything about the actual game LOL.

**Comment by HARUWEEN** [comment]
@FreeDenny9700 but you don't know how to actually ADD items, only replace LOL

**Comment by FreeDenny9700** [comment]
I made a server for you, do not lose time for that now. Bye

**Comment by HARUWEEN** [comment]
What are you saying kiddo?

**Comment by HARUWEEN** [comment]
@Devyre "that we're right" right? are you actually that much of a dingus? you guys are crying about files not adapted to season1 when literally 13 year olds know that theres a SCN Patcher LOL

**Comment by Devyre** [comment]
> @Devyre "that we're right" right? are you actually that much of a dingus? you guys are crying about files not adapted to season1 when literally 13 year olds know that theres a SCN Patcher LOL

And what does a patcher do? It changes the file so its usable, whats the definition of adapting again?
Oh and by the way, that SCN Patcher you're talking about isn't meant for this client.

You didn't even manage to add the items to the shop at first, why are you talking kid?

No idea why some 12y/o like you just randomly insults people on this repository, seems like your life doesn't give you much satisfaction.

**Comment by FreeDenny9700** [comment]
Yes, scn Reader and Patcher are for old EmuClient. If you compare HexCode Of Mac3 Dagger and FryPan Bat, you Can see that that file has a different structure. If you know how to adapt it, in-game (match) it work. Now i don't have a time to test it, if i have a time, in this days, i try to import this different model :)

PS: Genius you Can explain me how i Can modify structure Of SCN file? Thanks so much

**Comment by HARUWEEN** [comment]
Do you actually think I will explain you anything? LMAO.

**Comment by FreeDenny9700** [comment]
idiot response from a idiot person. Here you are on GitHub, open source community, if you not wan't help people, go out

**Comment by HARUWEEN** [comment]
LOL. you're the one not being able to fix frying pan, not me

**Comment by Devyre** [comment]
> LOL. you're the one not being able to fix frying pan, not me

And you don't wanna show proof because you have nothing to prove?
That's a nice logic kid, now please leave

Oh and didn't you say 0 files needed to be fixed? Now you're saying you fixed the frying pan? So blatantly lying dude

**Comment by HARUWEEN** [comment]
are you retarded? i DIDNT HAVE TO FIX ANYTHING. I literally added it and it worked

**Comment by wtfblub** [comment]
Calm down.

**Comment by FreeDenny9700** [comment]
Today i try an old tool for make SCN file. i hape that it work :)

**Comment by FreeDenny9700** [comment]
Client not read this type Of SCN Structure 

![screenshot_20161206-054033 2](https://cloud.githubusercontent.com/assets/19553583/20914347/5e1dd91e-bb7f-11e6-8018-685b0eef792d.png)

![screenshot_20161206-054033 3](https://cloud.githubusercontent.com/assets/19553583/20914400/b556d280-bb7f-11e6-8897-c987e0e3f19f.png)

**Comment by HARUWEEN** [comment]
ok

**Comment by FreeDenny9700** [comment]
i have tried to use tool but not work correctly for now. i wait our notice :)

**Comment by HARUWEEN** [comment]
SCNPatcher?

**Comment by FreeDenny9700** [comment]
No, SCN Creator, a tool for creating  scn from OBJ models in 3DS Studio Max. The tool works well in the game but the weapons have some minor problems

**Comment by HARUWEEN** [comment]
useless unless you want custom models

**Comment by FreeDenny9700** [comment]
i have all OBJ Model Of S4 League Weapon

**Comment by HARUWEEN** [comment]
oh haha then it's not useless

**Comment by FreeDenny9700** [comment]
if you want , i Can share this files with your

**Comment by wtfblub** [comment]
FYI: The Netsphere.Resource library contains parsing and writing of scn files. https://github.com/wtfblub/NetspherePirates/tree/master/src/Netsphere.Resource/Scene

**Comment by FreeDenny9700** [comment]
oh thanks wtfblub, today i try to import in-game a new model with your code.

**Comment by HARUWEEN** [comment]
Denny, what do you mean with "a new model" ?

**Comment by FreeDenny9700** [comment]
new SCN for example new sword weapon.
Blub script not work correctly for me. i need help xD

**Comment by HARUWEEN** [comment]
so you can import the new scn structures xD? and whats the problem with script

**Comment by FreeDenny9700** [comment]
client crash when i add new scn created with blub script. i have copied same structure of working weapon (taser) but not work... strange

**Comment by HARUWEEN** [comment]
you probably do something wrong

**Comment by FreeDenny9700** [comment]
it's very strange. how you import correctly Frypan in game? When i enter into room, after i equipped frypan, in lobby i crash. Probably is due to different structure of scn (animation) how you Can see from the screen.

**Comment by HARUWEEN** [comment]
if it really is because of the scn structure, you would crash in shop too, and there is no custom animations for bat.. only particles so that is also not the problem

**Comment by FreeDenny9700** [comment]
try to view this site, explain very good the situation http://forum.xentax.com/viewtopic.php?f=16&t=11201&start=15

**Comment by jazzup02** [comment]
BioAleks Please i need files the game from you and call me in facebook
https://www.facebook.com/jazzup02    
You very much

**Comment by FreeDenny9700** [comment]
BioAleks how you add AbilityType?
