### ISSUE TITLE
Game.exe Crash Help Me

### ISSUE THREAD

**Issue by s4archivos** [wtfblub/NetspherePirates#78]
|ERROR|ChatServer:82||System.Net.Sockets.SocketException (0x80004005): La operación de E/S se anuló por una salida de subproceso o por una solicitud de aplicación
   en BlubLib.Network.Transport.Sockets.TcpTransport.<ProcessReceive>d__27.MoveNext() 
System.Net.Sockets.SocketException (0x80004005): La operación de E/S se anuló por una salida de subproceso o por una solicitud de aplicación
   en BlubLib.Network.Transport.Sockets.TcpTransport.<ProcessReceive>d__27.MoveNext()
2016-10-17 00:10:32.3630|DEBUG|ProudPipe:80||Client 1001 disconnected 
2016-10-17 00:10:32.3730|ERROR|Program:101||UnhandledException 
System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en BlubLib.Network.Transport.Sockets.TcpTransport.Dispose()
   en BlubLib.Network.Session.Dispose()
   en BlubLib.Network.Transport.Sockets.TcpTransport.<ProcessReceive>d__27.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   en System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   en System.Threading.ThreadPoolWorkQueue.Dispatch()
   en System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by s4archivos** [comment]
That happens to me every time I press the button + f4 atl Help me

**Comment by wtfblub** [comment]
What button?

**Comment by s4archivos** [comment]
every time I entered the game and close with alt + f4 the game.exe console automatically closes and also when I create a new account sometimes not the weapon is equipped and console comes out that not ah could equip the weapon and game.exe closes the console

**Comment by s4archivos** [comment]
when I close the game with alt+f4 button code that appears in the console and closed.

**Comment by s4archivos** [comment]
http://prntscr.com/cvn2eo image to error

**Comment by BioAleks** [comment]
About equip after first character create: https://github.com/wtfblub/NetspherePirates/issues/18
It's no fixed. Just relog to server.

**Comment by foantom00** [comment]
Help Me http://prnt.sc/edtu2i

**Comment by wtfblub** [comment]
@foantom00 https://github.com/wtfblub/NetspherePirates/blob/master/README.md
