### ISSUE TITLE
Licenses not saving after rejoining the server

### ISSUE THREAD

**Issue by Vyre** [wtfblub/NetspherePirates#8]
Don't know if this problem is on my end or actually not implemented, but thought its worth reporting this issue.

**Comment by BioAleks** [comment]
Licenses saving after player complete it (but only for client). After rejoin - client no have this licenses. Licenses no saving in DB.
In command line server we see that I complete this license. 
When server start saving - server drop error (players - saving, licenses - no).

Adding server save error.
[licenses error.txt](https://github.com/wtfblub/NetspherePirates/files/367298/licenses.error.txt)

**Comment by Saitama-Kun** [comment]
The Best Solution is Editing The Game.json file (Found in Game Emulator Files) And Setting its enable_license_requirement To False Exactly like this : http://bit.ly/2atXjk7

**Comment by BioAleks** [comment]
This post for server error, not for questions. 
Of course everyone know how to do this (if no - no install server).

**Comment by BioAleks** [comment]
Blub, add "Bug" label.

**Comment by wtfblub** [comment]
Fixed with the new database code e20cd633202ca719a8070ee14008cbdfe48c6a20
