### ISSUE TITLE
Question: std?

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#82]
Blub, you discover wtf is that (std mode)?
Interesting what is this with all details, description.
Not only mode name...

**Comment by wtfblub** [comment]
std?

**Comment by BioAleks** [comment]
Yes. "Std" game mode.
You have this in code too.

From client (mapinfo):
`enableMode2=std`
From server code:
`public enum GameRule : uint`
`SemiTouchdown = 6, // Dev`

**Comment by BioAleks** [comment]
So...?

**Comment by wtfblub** [comment]
This mode was never implemented so only the developers know.

**Comment by Joraileds** [comment]
I think is something like a survival mode game cause it appears in old beta client

**Comment by BioAleks** [comment]
> I think is something like a survival mode game cause it appears in old beta client

I know that files have "survival" mode. 
I like design of "hive" map (unreleased).

**Comment by BioAleks** [comment]
Blub, what you do with this mode? Or what is this be?

**Comment by wtfblub** [comment]
Nothing. Like I said its not implemented. Pretty sure the client just crashes if you join a room with this game mode.
