### ISSUE TITLE
New Client Version

### ISSUE THREAD

**Issue by FreeDenny9700** [wtfblub/NetspherePirates#86]
Why did You have decide to change client version?

**Comment by wtfblub** [comment]
Because it makes a few things easier.

**Comment by FreeDenny9700** [comment]
You release new client version for this file server?

**Comment by BioAleks** [comment]
Which version will be?

**Comment by wtfblub** [comment]
I'll upload the client when i updated everything. Currently there is no reason for you to use the new branch.

**Comment by FreeDenny9700** [comment]
Ok, thanks for response

**Comment by s4archivos** [comment]
The client will be patch 2 of season 1?
