### ISSUE TITLE
SharpLzo Error on Ubuntu Server

### ISSUE THREAD

**Issue by FreeDenny9700** [wtfblub/NetspherePirates#87]
SharpLzo Error when i enter into server with my account.

![lzoerror](https://cloud.githubusercontent.com/assets/19553583/19829974/b89b6a86-9dee-11e6-88ac-24af080537f8.png)

[DEBUG.txt](https://github.com/wtfblub/NetspherePirates/files/559941/DEBUG.txt)

**Comment by wtfblub** [comment]
Is liblzo.so in the folder?

**Comment by FreeDenny9700** [comment]
Yes, it's all compilated and in folder.

**Comment by FreeDenny9700** [comment]
EDIT: 
This error is due to the public IP configuration with listener to 0.0.0.0
