### ISSUE TITLE
GM Commands

### ISSUE THREAD

**Issue by AminadeusMozart** [wtfblub/NetspherePirates#88]
Where i can find the commands ? =/

**Comment by BioAleks** [comment]
https://github.com/wtfblub/NetspherePirates/tree/master/src/Game/Commands

**Comment by Joraileds** [comment]
Only works 3 or 4 commands. You can add those commands editing files but game crash.

**Comment by wtfblub** [comment]
All commands work but keep in my mind: The commands found in the client are not commands I'm using and I'm never going to implement them with the same name! You have to use commands found in the server source code.

**Comment by shanzenos** [comment]
Seems as though the only 2 commands I could get working were inventory and server. No kick or ban commands yet implemented?
