### ISSUE TITLE
Question: method 'mysql_native_password' failed?

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#97]
Hello Blub.
I reinstall windows 7, install all programs and etc.
Try to start server and see:
`MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'localhost' for user 'test' using method 'mysql_native_password' failed with message: Access denied for user 'test'@'localhost' (using password: YES) ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'test'@'localhost' (using password: YES)`

Do you know what is the problem?
Password and all another settings - ok.
Web authorization (php my admin) - working, navicat auth - working, but server say this error.
Hosts file windows no modified.

**Comment by wtfblub** [comment]
Do you use a empty password? If yes you have to use `""` in the config file

**Comment by BioAleks** [comment]
No empty. It's why password = YES.

**Comment by wtfblub** [comment]
Show your config file please.

**Comment by BioAleks** [comment]
[auth.txt](https://github.com/wtfblub/NetspherePirates/files/611590/auth.txt)

**Comment by wtfblub** [comment]
Double check the password and make sure the host you use is allowed for the mysql user. You can also try to put the password inside ""

**Comment by BioAleks** [comment]
I many times check before all data that i need.
I see problem: server no read new .hjson data and use old (i don't know where server find it if use same file oO). I save new data no one time, but only now working.
