### ISSUE TITLE
System.Net.Sockets.SocketException (0x80004005)

### ISSUE THREAD

**Issue by s4archivos** [wtfblub/NetspherePirates#99]
System.Net.Sockets.SocketException (0x80004005): The I / O operation was aborted by a thread exit or by an application request
    In BlubLib.Network.Transport.Sockets.TcpTransport. <ProcessReceive> d__27.MoveNext ()

Help!

I have installed .net famework 4.6 and 4.6.1 and 4.6.2 also c ++ 2015 64bits and 32bits update 1 and update 3

Something else should install?

**Comment by wtfblub** [comment]
You already reported this in #78
